// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cordic_cordic,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.814250,HLS_SYN_LAT=13,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1181,HLS_SYN_LUT=2750,HLS_VERSION=2020_2}" *)

module cordic (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        full_alpha,
        sin_out,
        sin_out_ap_vld,
        cos_out,
        cos_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [16:0] full_alpha;
output  [15:0] sin_out;
output   sin_out_ap_vld;
output  [15:0] cos_out;
output   cos_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg sin_out_ap_vld;
reg[15:0] cos_out;
reg cos_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] flag_V_fu_260_p3;
reg   [1:0] flag_V_reg_1631;
reg   [1:0] flag_V_reg_1631_pp0_iter1_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter2_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter3_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter4_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter5_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter6_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter7_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter8_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter9_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter10_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter11_reg;
reg   [1:0] flag_V_reg_1631_pp0_iter12_reg;
reg   [0:0] tmp_reg_1635;
reg   [0:0] tmp_reg_1635_pp0_iter1_reg;
reg   [0:0] tmp_reg_1635_pp0_iter2_reg;
reg   [0:0] tmp_reg_1635_pp0_iter3_reg;
reg   [0:0] tmp_reg_1635_pp0_iter4_reg;
reg   [0:0] tmp_reg_1635_pp0_iter5_reg;
reg   [0:0] tmp_reg_1635_pp0_iter6_reg;
wire   [16:0] add_ln68_fu_292_p2;
reg   [16:0] add_ln68_reg_1643;
reg   [0:0] tmp_2_reg_1648;
reg   [0:0] tmp_2_reg_1648_pp0_iter1_reg;
reg   [0:0] tmp_2_reg_1648_pp0_iter2_reg;
reg   [0:0] tmp_2_reg_1648_pp0_iter3_reg;
reg   [0:0] tmp_2_reg_1648_pp0_iter4_reg;
reg   [0:0] tmp_2_reg_1648_pp0_iter5_reg;
reg   [0:0] tmp_2_reg_1648_pp0_iter6_reg;
reg   [0:0] tmp_3_reg_1654;
wire   [16:0] add_ln1496_1_fu_326_p2;
reg   [16:0] add_ln1496_1_reg_1659;
reg   [0:0] tmp_4_reg_1664;
reg   [0:0] tmp_4_reg_1664_pp0_iter2_reg;
reg   [0:0] tmp_4_reg_1664_pp0_iter3_reg;
reg   [0:0] tmp_4_reg_1664_pp0_iter4_reg;
reg   [0:0] tmp_4_reg_1664_pp0_iter5_reg;
reg   [0:0] tmp_4_reg_1664_pp0_iter6_reg;
reg   [0:0] tmp_5_reg_1670;
wire   [16:0] add_ln1496_3_fu_360_p2;
reg   [16:0] add_ln1496_3_reg_1675;
reg   [0:0] tmp_6_reg_1680;
reg   [0:0] tmp_6_reg_1680_pp0_iter3_reg;
reg   [0:0] tmp_6_reg_1680_pp0_iter4_reg;
reg   [0:0] tmp_6_reg_1680_pp0_iter5_reg;
reg   [0:0] tmp_6_reg_1680_pp0_iter6_reg;
reg   [0:0] tmp_8_reg_1686;
wire   [16:0] add_ln1496_5_fu_394_p2;
reg   [16:0] add_ln1496_5_reg_1691;
reg   [0:0] tmp_9_reg_1696;
reg   [0:0] tmp_9_reg_1696_pp0_iter4_reg;
reg   [0:0] tmp_9_reg_1696_pp0_iter5_reg;
reg   [0:0] tmp_9_reg_1696_pp0_iter6_reg;
reg   [0:0] tmp_9_reg_1696_pp0_iter7_reg;
reg   [0:0] tmp_10_reg_1702;
wire   [16:0] add_ln1496_7_fu_428_p2;
reg   [16:0] add_ln1496_7_reg_1707;
reg   [0:0] tmp_11_reg_1712;
reg   [0:0] tmp_11_reg_1712_pp0_iter5_reg;
reg   [0:0] tmp_11_reg_1712_pp0_iter6_reg;
reg   [0:0] tmp_11_reg_1712_pp0_iter7_reg;
reg   [0:0] tmp_12_reg_1718;
wire   [16:0] add_ln1496_9_fu_462_p2;
reg   [16:0] add_ln1496_9_reg_1723;
reg   [0:0] tmp_13_reg_1728;
reg   [0:0] tmp_13_reg_1728_pp0_iter6_reg;
reg   [0:0] tmp_13_reg_1728_pp0_iter7_reg;
reg   [0:0] tmp_13_reg_1728_pp0_iter8_reg;
reg   [0:0] tmp_14_reg_1734;
wire   [16:0] add_ln1496_11_fu_496_p2;
reg   [16:0] add_ln1496_11_reg_1739;
reg   [0:0] tmp_15_reg_1744;
reg   [0:0] tmp_15_reg_1744_pp0_iter7_reg;
reg   [0:0] tmp_15_reg_1744_pp0_iter8_reg;
reg   [0:0] tmp_16_reg_1750;
wire   [15:0] select_ln1496_5_fu_690_p3;
reg   [15:0] select_ln1496_5_reg_1755;
wire   [15:0] select_ln1496_6_fu_697_p3;
reg   [15:0] select_ln1496_6_reg_1761;
reg   [11:0] trunc_ln1333_3_reg_1767;
reg   [11:0] trunc_ln1333_4_reg_1772;
wire   [16:0] add_ln1496_13_fu_736_p2;
reg   [16:0] add_ln1496_13_reg_1777;
reg   [0:0] tmp_17_reg_1782;
reg   [0:0] tmp_17_reg_1782_pp0_iter8_reg;
reg   [0:0] tmp_17_reg_1782_pp0_iter9_reg;
reg   [0:0] tmp_18_reg_1788;
wire   [15:0] select_ln1496_11_fu_850_p3;
reg   [15:0] select_ln1496_11_reg_1793;
wire   [15:0] select_ln1496_12_fu_857_p3;
reg   [15:0] select_ln1496_12_reg_1799;
reg   [9:0] trunc_ln1333_7_reg_1805;
reg   [9:0] trunc_ln1333_8_reg_1810;
wire   [16:0] add_ln1496_15_fu_896_p2;
reg   [16:0] add_ln1496_15_reg_1815;
reg   [0:0] tmp_19_reg_1820;
reg   [0:0] tmp_19_reg_1820_pp0_iter9_reg;
reg   [0:0] tmp_20_reg_1826;
wire   [15:0] select_ln1496_17_fu_1010_p3;
reg   [15:0] select_ln1496_17_reg_1831;
wire   [15:0] select_ln1496_18_fu_1017_p3;
reg   [15:0] select_ln1496_18_reg_1837;
reg   [7:0] trunc_ln1333_2_reg_1843;
reg   [7:0] trunc_ln1333_10_reg_1848;
wire   [16:0] add_ln1496_17_fu_1056_p2;
reg   [16:0] add_ln1496_17_reg_1853;
reg   [0:0] tmp_21_reg_1858;
reg   [0:0] tmp_21_reg_1858_pp0_iter10_reg;
reg   [0:0] tmp_22_reg_1864;
wire   [15:0] select_ln1496_23_fu_1170_p3;
reg   [15:0] select_ln1496_23_reg_1869;
wire   [15:0] select_ln1496_24_fu_1177_p3;
reg   [15:0] select_ln1496_24_reg_1875;
reg   [5:0] trunc_ln1333_13_reg_1881;
reg   [5:0] trunc_ln1333_14_reg_1886;
wire   [16:0] add_ln1496_19_fu_1216_p2;
reg   [16:0] add_ln1496_19_reg_1891;
reg   [0:0] tmp_23_reg_1896;
reg   [0:0] tmp_24_reg_1902;
wire   [15:0] select_ln1496_29_fu_1330_p3;
reg   [15:0] select_ln1496_29_reg_1907;
wire   [15:0] select_ln1496_30_fu_1337_p3;
reg   [15:0] select_ln1496_30_reg_1913;
wire   [16:0] add_ln1496_21_fu_1356_p2;
reg   [16:0] add_ln1496_21_reg_1919;
reg   [0:0] tmp_25_reg_1924;
reg   [3:0] trunc_ln1333_17_reg_1930;
reg   [3:0] trunc_ln1333_18_reg_1935;
reg   [0:0] tmp_26_reg_1940;
wire   [16:0] add_ln1496_23_fu_1450_p2;
reg   [16:0] add_ln1496_23_reg_1945;
wire   [15:0] select_ln1496_35_fu_1516_p3;
reg   [15:0] select_ln1496_35_reg_1950;
wire   [15:0] select_ln1496_36_fu_1524_p3;
reg   [15:0] select_ln1496_36_reg_1956;
wire   [16:0] select_ln1496_37_fu_1540_p3;
reg   [16:0] select_ln1496_37_reg_1962;
reg   [1:0] trunc_ln1333_21_reg_1967;
reg   [1:0] trunc_ln1333_22_reg_1972;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0_01001;
wire   [15:0] grp_fu_200_p2;
wire   [15:0] mycos_V_fu_1621_p3;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln1495_fu_218_p2;
wire   [16:0] alpha_V_1_fu_224_p2;
wire   [0:0] icmp_ln1494_fu_206_p2;
wire   [16:0] alpha_V_fu_212_p2;
wire   [16:0] select_ln24_fu_230_p3;
wire   [0:0] or_ln1494_fu_254_p2;
wire   [1:0] select_ln1494_1_fu_246_p3;
wire   [16:0] alpha_V_2_fu_238_p3;
wire   [0:0] tmp_1_fu_276_p3;
wire   [16:0] select_ln68_fu_284_p3;
wire   [16:0] add_ln1496_fu_321_p2;
wire   [16:0] select_ln1496_1_fu_314_p3;
wire   [16:0] add_ln1496_2_fu_355_p2;
wire   [16:0] select_ln1496_4_fu_348_p3;
wire   [16:0] add_ln1496_4_fu_389_p2;
wire   [16:0] select_ln1496_7_fu_382_p3;
wire   [16:0] add_ln1496_6_fu_423_p2;
wire   [16:0] select_ln1496_10_fu_416_p3;
wire   [16:0] add_ln1496_8_fu_457_p2;
wire   [16:0] select_ln1496_13_fu_450_p3;
wire   [16:0] add_ln1496_10_fu_491_p2;
wire   [16:0] select_ln1496_16_fu_484_p3;
wire   [13:0] select_ln703_2_fu_532_p3;
wire   [13:0] select_ln703_fu_518_p3;
wire   [13:0] select_ln1333_fu_546_p3;
wire   [14:0] select_ln703_3_fu_539_p3;
wire   [14:0] select_ln703_1_fu_525_p3;
wire  signed [14:0] select_ln1496_fu_557_p3;
wire   [12:0] trunc_ln2_fu_568_p4;
wire   [11:0] lshr_ln1333_1_fu_582_p4;
wire   [14:0] zext_ln1496_fu_553_p1;
wire  signed [14:0] sext_ln1333_fu_578_p1;
wire  signed [15:0] sext_ln1496_fu_564_p1;
wire   [15:0] zext_ln1333_fu_592_p1;
wire   [14:0] add_ln703_1_fu_608_p2;
wire   [14:0] sub_ln703_4_fu_596_p2;
wire   [14:0] select_ln1496_2_fu_620_p3;
wire   [15:0] sub_ln703_5_fu_614_p2;
wire   [15:0] add_ln703_fu_602_p2;
wire   [15:0] select_ln1496_3_fu_631_p3;
wire   [12:0] trunc_ln1333_1_fu_638_p4;
wire   [11:0] tmp_7_fu_652_p4;
wire   [15:0] zext_ln1496_1_fu_627_p1;
wire  signed [15:0] sext_ln1333_1_fu_648_p1;
wire   [15:0] zext_ln1333_1_fu_662_p1;
wire   [15:0] add_ln703_3_fu_678_p2;
wire   [15:0] sub_ln703_6_fu_666_p2;
wire   [15:0] sub_ln703_7_fu_684_p2;
wire   [15:0] add_ln703_2_fu_672_p2;
wire   [16:0] add_ln1496_12_fu_731_p2;
wire   [16:0] select_ln1496_19_fu_724_p3;
wire  signed [15:0] sext_ln1333_2_fu_758_p1;
wire  signed [15:0] sext_ln1333_3_fu_761_p1;
wire   [15:0] add_ln703_11_fu_774_p2;
wire   [15:0] sub_ln703_8_fu_764_p2;
wire   [15:0] sub_ln703_9_fu_779_p2;
wire   [15:0] add_ln703_4_fu_769_p2;
wire   [15:0] select_ln1496_9_fu_791_p3;
wire   [10:0] trunc_ln1333_5_fu_798_p4;
wire   [15:0] select_ln1496_8_fu_784_p3;
wire   [10:0] trunc_ln1333_6_fu_812_p4;
wire  signed [15:0] sext_ln1333_4_fu_808_p1;
wire  signed [15:0] sext_ln1333_5_fu_822_p1;
wire   [15:0] add_ln703_15_fu_838_p2;
wire   [15:0] sub_ln703_10_fu_826_p2;
wire   [15:0] sub_ln703_11_fu_844_p2;
wire   [15:0] add_ln703_5_fu_832_p2;
wire   [16:0] add_ln1496_14_fu_891_p2;
wire   [16:0] select_ln1496_22_fu_884_p3;
wire  signed [15:0] sext_ln1333_6_fu_918_p1;
wire  signed [15:0] sext_ln1333_7_fu_921_p1;
wire   [15:0] add_ln703_16_fu_934_p2;
wire   [15:0] sub_ln703_12_fu_924_p2;
wire   [15:0] sub_ln703_13_fu_939_p2;
wire   [15:0] add_ln703_6_fu_929_p2;
wire   [15:0] select_ln1496_15_fu_951_p3;
wire   [8:0] trunc_ln1333_9_fu_958_p4;
wire   [15:0] select_ln1496_14_fu_944_p3;
wire   [8:0] trunc_ln1333_s_fu_972_p4;
wire  signed [15:0] sext_ln1333_8_fu_968_p1;
wire  signed [15:0] sext_ln1333_9_fu_982_p1;
wire   [15:0] add_ln703_17_fu_998_p2;
wire   [15:0] sub_ln703_14_fu_986_p2;
wire   [15:0] sub_ln703_15_fu_1004_p2;
wire   [15:0] add_ln703_7_fu_992_p2;
wire   [16:0] add_ln1496_16_fu_1051_p2;
wire   [16:0] select_ln1496_25_fu_1044_p3;
wire  signed [15:0] sext_ln1333_10_fu_1078_p1;
wire  signed [15:0] sext_ln1333_11_fu_1081_p1;
wire   [15:0] add_ln703_18_fu_1094_p2;
wire   [15:0] sub_ln703_16_fu_1084_p2;
wire   [15:0] sub_ln703_17_fu_1099_p2;
wire   [15:0] add_ln703_8_fu_1089_p2;
wire   [15:0] select_ln1496_21_fu_1111_p3;
wire   [6:0] trunc_ln1333_11_fu_1118_p4;
wire   [15:0] select_ln1496_20_fu_1104_p3;
wire   [6:0] trunc_ln1333_12_fu_1132_p4;
wire  signed [15:0] sext_ln1333_12_fu_1128_p1;
wire  signed [15:0] sext_ln1333_13_fu_1142_p1;
wire   [15:0] add_ln703_19_fu_1158_p2;
wire   [15:0] sub_ln703_18_fu_1146_p2;
wire   [15:0] sub_ln703_19_fu_1164_p2;
wire   [15:0] add_ln703_9_fu_1152_p2;
wire   [16:0] add_ln1496_18_fu_1211_p2;
wire   [16:0] select_ln1496_28_fu_1204_p3;
wire  signed [15:0] sext_ln1333_14_fu_1238_p1;
wire  signed [15:0] sext_ln1333_15_fu_1241_p1;
wire   [15:0] add_ln703_20_fu_1254_p2;
wire   [15:0] sub_ln703_20_fu_1244_p2;
wire   [15:0] sub_ln703_21_fu_1259_p2;
wire   [15:0] add_ln703_10_fu_1249_p2;
wire   [15:0] select_ln1496_27_fu_1271_p3;
wire   [4:0] trunc_ln1333_15_fu_1278_p4;
wire   [15:0] select_ln1496_26_fu_1264_p3;
wire   [4:0] trunc_ln1333_16_fu_1292_p4;
wire  signed [15:0] sext_ln1333_16_fu_1288_p1;
wire  signed [15:0] sext_ln1333_17_fu_1302_p1;
wire   [15:0] add_ln703_22_fu_1318_p2;
wire   [15:0] sub_ln703_22_fu_1306_p2;
wire   [15:0] sub_ln703_23_fu_1324_p2;
wire   [15:0] add_ln703_21_fu_1312_p2;
wire   [16:0] add_ln1496_20_fu_1351_p2;
wire   [16:0] select_ln1496_31_fu_1344_p3;
wire  signed [15:0] sext_ln1333_18_fu_1398_p1;
wire  signed [15:0] sext_ln1333_19_fu_1401_p1;
wire   [15:0] add_ln703_23_fu_1414_p2;
wire   [15:0] sub_ln703_24_fu_1404_p2;
wire   [15:0] sub_ln703_25_fu_1419_p2;
wire   [15:0] add_ln703_12_fu_1409_p2;
wire   [16:0] add_ln1496_22_fu_1445_p2;
wire   [16:0] select_ln1496_34_fu_1438_p3;
wire   [15:0] select_ln1496_33_fu_1431_p3;
wire   [2:0] trunc_ln1333_19_fu_1464_p4;
wire   [15:0] select_ln1496_32_fu_1424_p3;
wire   [2:0] trunc_ln1333_20_fu_1478_p4;
wire  signed [15:0] sext_ln1333_20_fu_1474_p1;
wire  signed [15:0] sext_ln1333_21_fu_1488_p1;
wire   [0:0] tmp_27_fu_1456_p3;
wire   [15:0] add_ln703_24_fu_1504_p2;
wire   [15:0] sub_ln703_26_fu_1492_p2;
wire   [15:0] sub_ln703_27_fu_1510_p2;
wire   [15:0] add_ln703_13_fu_1498_p2;
wire   [0:0] tmp_28_fu_1532_p3;
wire   [16:0] add_ln1496_24_fu_1568_p2;
wire   [16:0] add_ln1496_25_fu_1573_p2;
wire  signed [15:0] sext_ln1333_22_fu_1586_p1;
wire  signed [15:0] sext_ln1333_23_fu_1589_p1;
wire   [0:0] tmp_29_fu_1578_p3;
wire   [15:0] sub_ln703_29_fu_1607_p2;
wire   [15:0] add_ln703_14_fu_1597_p2;
wire   [15:0] add_ln703_25_fu_1602_p2;
wire   [15:0] sub_ln703_28_fu_1592_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to12;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln1496_11_reg_1739 <= add_ln1496_11_fu_496_p2;
        add_ln1496_13_reg_1777 <= add_ln1496_13_fu_736_p2;
        add_ln1496_15_reg_1815 <= add_ln1496_15_fu_896_p2;
        add_ln1496_17_reg_1853 <= add_ln1496_17_fu_1056_p2;
        add_ln1496_19_reg_1891 <= add_ln1496_19_fu_1216_p2;
        add_ln1496_21_reg_1919 <= add_ln1496_21_fu_1356_p2;
        add_ln1496_23_reg_1945 <= add_ln1496_23_fu_1450_p2;
        add_ln1496_3_reg_1675 <= add_ln1496_3_fu_360_p2;
        add_ln1496_5_reg_1691 <= add_ln1496_5_fu_394_p2;
        add_ln1496_7_reg_1707 <= add_ln1496_7_fu_428_p2;
        add_ln1496_9_reg_1723 <= add_ln1496_9_fu_462_p2;
        flag_V_reg_1631_pp0_iter10_reg <= flag_V_reg_1631_pp0_iter9_reg;
        flag_V_reg_1631_pp0_iter11_reg <= flag_V_reg_1631_pp0_iter10_reg;
        flag_V_reg_1631_pp0_iter12_reg <= flag_V_reg_1631_pp0_iter11_reg;
        flag_V_reg_1631_pp0_iter2_reg <= flag_V_reg_1631_pp0_iter1_reg;
        flag_V_reg_1631_pp0_iter3_reg <= flag_V_reg_1631_pp0_iter2_reg;
        flag_V_reg_1631_pp0_iter4_reg <= flag_V_reg_1631_pp0_iter3_reg;
        flag_V_reg_1631_pp0_iter5_reg <= flag_V_reg_1631_pp0_iter4_reg;
        flag_V_reg_1631_pp0_iter6_reg <= flag_V_reg_1631_pp0_iter5_reg;
        flag_V_reg_1631_pp0_iter7_reg <= flag_V_reg_1631_pp0_iter6_reg;
        flag_V_reg_1631_pp0_iter8_reg <= flag_V_reg_1631_pp0_iter7_reg;
        flag_V_reg_1631_pp0_iter9_reg <= flag_V_reg_1631_pp0_iter8_reg;
        select_ln1496_11_reg_1793 <= select_ln1496_11_fu_850_p3;
        select_ln1496_12_reg_1799 <= select_ln1496_12_fu_857_p3;
        select_ln1496_17_reg_1831 <= select_ln1496_17_fu_1010_p3;
        select_ln1496_18_reg_1837 <= select_ln1496_18_fu_1017_p3;
        select_ln1496_23_reg_1869 <= select_ln1496_23_fu_1170_p3;
        select_ln1496_24_reg_1875 <= select_ln1496_24_fu_1177_p3;
        select_ln1496_29_reg_1907 <= select_ln1496_29_fu_1330_p3;
        select_ln1496_30_reg_1913 <= select_ln1496_30_fu_1337_p3;
        select_ln1496_35_reg_1950 <= select_ln1496_35_fu_1516_p3;
        select_ln1496_36_reg_1956 <= select_ln1496_36_fu_1524_p3;
        select_ln1496_37_reg_1962[2] <= select_ln1496_37_fu_1540_p3[2];
        select_ln1496_5_reg_1755 <= select_ln1496_5_fu_690_p3;
        select_ln1496_6_reg_1761 <= select_ln1496_6_fu_697_p3;
        tmp_10_reg_1702 <= add_ln1496_5_fu_394_p2[32'd16];
        tmp_11_reg_1712 <= add_ln1496_7_fu_428_p2[32'd16];
        tmp_11_reg_1712_pp0_iter5_reg <= tmp_11_reg_1712;
        tmp_11_reg_1712_pp0_iter6_reg <= tmp_11_reg_1712_pp0_iter5_reg;
        tmp_11_reg_1712_pp0_iter7_reg <= tmp_11_reg_1712_pp0_iter6_reg;
        tmp_12_reg_1718 <= add_ln1496_7_fu_428_p2[32'd16];
        tmp_13_reg_1728 <= add_ln1496_9_fu_462_p2[32'd16];
        tmp_13_reg_1728_pp0_iter6_reg <= tmp_13_reg_1728;
        tmp_13_reg_1728_pp0_iter7_reg <= tmp_13_reg_1728_pp0_iter6_reg;
        tmp_13_reg_1728_pp0_iter8_reg <= tmp_13_reg_1728_pp0_iter7_reg;
        tmp_14_reg_1734 <= add_ln1496_9_fu_462_p2[32'd16];
        tmp_15_reg_1744 <= add_ln1496_11_fu_496_p2[32'd16];
        tmp_15_reg_1744_pp0_iter7_reg <= tmp_15_reg_1744;
        tmp_15_reg_1744_pp0_iter8_reg <= tmp_15_reg_1744_pp0_iter7_reg;
        tmp_16_reg_1750 <= add_ln1496_11_fu_496_p2[32'd16];
        tmp_17_reg_1782 <= add_ln1496_13_fu_736_p2[32'd16];
        tmp_17_reg_1782_pp0_iter8_reg <= tmp_17_reg_1782;
        tmp_17_reg_1782_pp0_iter9_reg <= tmp_17_reg_1782_pp0_iter8_reg;
        tmp_18_reg_1788 <= add_ln1496_13_fu_736_p2[32'd16];
        tmp_19_reg_1820 <= add_ln1496_15_fu_896_p2[32'd16];
        tmp_19_reg_1820_pp0_iter9_reg <= tmp_19_reg_1820;
        tmp_20_reg_1826 <= add_ln1496_15_fu_896_p2[32'd16];
        tmp_21_reg_1858 <= add_ln1496_17_fu_1056_p2[32'd16];
        tmp_21_reg_1858_pp0_iter10_reg <= tmp_21_reg_1858;
        tmp_22_reg_1864 <= add_ln1496_17_fu_1056_p2[32'd16];
        tmp_23_reg_1896 <= add_ln1496_19_fu_1216_p2[32'd16];
        tmp_24_reg_1902 <= add_ln1496_19_fu_1216_p2[32'd16];
        tmp_25_reg_1924 <= add_ln1496_21_fu_1356_p2[32'd16];
        tmp_26_reg_1940 <= add_ln1496_21_fu_1356_p2[32'd16];
        tmp_2_reg_1648_pp0_iter2_reg <= tmp_2_reg_1648_pp0_iter1_reg;
        tmp_2_reg_1648_pp0_iter3_reg <= tmp_2_reg_1648_pp0_iter2_reg;
        tmp_2_reg_1648_pp0_iter4_reg <= tmp_2_reg_1648_pp0_iter3_reg;
        tmp_2_reg_1648_pp0_iter5_reg <= tmp_2_reg_1648_pp0_iter4_reg;
        tmp_2_reg_1648_pp0_iter6_reg <= tmp_2_reg_1648_pp0_iter5_reg;
        tmp_4_reg_1664_pp0_iter2_reg <= tmp_4_reg_1664;
        tmp_4_reg_1664_pp0_iter3_reg <= tmp_4_reg_1664_pp0_iter2_reg;
        tmp_4_reg_1664_pp0_iter4_reg <= tmp_4_reg_1664_pp0_iter3_reg;
        tmp_4_reg_1664_pp0_iter5_reg <= tmp_4_reg_1664_pp0_iter4_reg;
        tmp_4_reg_1664_pp0_iter6_reg <= tmp_4_reg_1664_pp0_iter5_reg;
        tmp_6_reg_1680 <= add_ln1496_3_fu_360_p2[32'd16];
        tmp_6_reg_1680_pp0_iter3_reg <= tmp_6_reg_1680;
        tmp_6_reg_1680_pp0_iter4_reg <= tmp_6_reg_1680_pp0_iter3_reg;
        tmp_6_reg_1680_pp0_iter5_reg <= tmp_6_reg_1680_pp0_iter4_reg;
        tmp_6_reg_1680_pp0_iter6_reg <= tmp_6_reg_1680_pp0_iter5_reg;
        tmp_8_reg_1686 <= add_ln1496_3_fu_360_p2[32'd16];
        tmp_9_reg_1696 <= add_ln1496_5_fu_394_p2[32'd16];
        tmp_9_reg_1696_pp0_iter4_reg <= tmp_9_reg_1696;
        tmp_9_reg_1696_pp0_iter5_reg <= tmp_9_reg_1696_pp0_iter4_reg;
        tmp_9_reg_1696_pp0_iter6_reg <= tmp_9_reg_1696_pp0_iter5_reg;
        tmp_9_reg_1696_pp0_iter7_reg <= tmp_9_reg_1696_pp0_iter6_reg;
        tmp_reg_1635_pp0_iter2_reg <= tmp_reg_1635_pp0_iter1_reg;
        tmp_reg_1635_pp0_iter3_reg <= tmp_reg_1635_pp0_iter2_reg;
        tmp_reg_1635_pp0_iter4_reg <= tmp_reg_1635_pp0_iter3_reg;
        tmp_reg_1635_pp0_iter5_reg <= tmp_reg_1635_pp0_iter4_reg;
        tmp_reg_1635_pp0_iter6_reg <= tmp_reg_1635_pp0_iter5_reg;
        trunc_ln1333_10_reg_1848 <= {{select_ln1496_17_fu_1010_p3[15:8]}};
        trunc_ln1333_13_reg_1881 <= {{select_ln1496_24_fu_1177_p3[15:10]}};
        trunc_ln1333_14_reg_1886 <= {{select_ln1496_23_fu_1170_p3[15:10]}};
        trunc_ln1333_17_reg_1930 <= {{select_ln1496_30_fu_1337_p3[15:12]}};
        trunc_ln1333_18_reg_1935 <= {{select_ln1496_29_fu_1330_p3[15:12]}};
        trunc_ln1333_21_reg_1967 <= {{select_ln1496_36_fu_1524_p3[15:14]}};
        trunc_ln1333_22_reg_1972 <= {{select_ln1496_35_fu_1516_p3[15:14]}};
        trunc_ln1333_2_reg_1843 <= {{select_ln1496_18_fu_1017_p3[15:8]}};
        trunc_ln1333_3_reg_1767 <= {{select_ln1496_6_fu_697_p3[15:4]}};
        trunc_ln1333_4_reg_1772 <= {{select_ln1496_5_fu_690_p3[15:4]}};
        trunc_ln1333_7_reg_1805 <= {{select_ln1496_12_fu_857_p3[15:6]}};
        trunc_ln1333_8_reg_1810 <= {{select_ln1496_11_fu_850_p3[15:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln1496_1_reg_1659 <= add_ln1496_1_fu_326_p2;
        add_ln68_reg_1643 <= add_ln68_fu_292_p2;
        flag_V_reg_1631 <= flag_V_fu_260_p3;
        flag_V_reg_1631_pp0_iter1_reg <= flag_V_reg_1631;
        tmp_2_reg_1648 <= add_ln68_fu_292_p2[32'd16];
        tmp_2_reg_1648_pp0_iter1_reg <= tmp_2_reg_1648;
        tmp_3_reg_1654 <= add_ln68_fu_292_p2[32'd16];
        tmp_4_reg_1664 <= add_ln1496_1_fu_326_p2[32'd16];
        tmp_5_reg_1670 <= add_ln1496_1_fu_326_p2[32'd16];
        tmp_reg_1635 <= alpha_V_2_fu_238_p3[32'd16];
        tmp_reg_1635_pp0_iter1_reg <= tmp_reg_1635;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to12 = 1'b1;
    end else begin
        ap_idle_pp0_0to12 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to12 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(flag_V_reg_1631_pp0_iter12_reg == 2'd2) & ~(flag_V_reg_1631_pp0_iter12_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        cos_out = mycos_V_fu_1621_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (flag_V_reg_1631_pp0_iter12_reg == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (flag_V_reg_1631_pp0_iter12_reg == 2'd3)))) begin
        cos_out = grp_fu_200_p2;
    end else begin
        cos_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (flag_V_reg_1631_pp0_iter12_reg == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (flag_V_reg_1631_pp0_iter12_reg == 2'd3)) | (~(flag_V_reg_1631_pp0_iter12_reg == 2'd2) & ~(flag_V_reg_1631_pp0_iter12_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1)))) begin
        cos_out_ap_vld = 1'b1;
    end else begin
        cos_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        sin_out_ap_vld = 1'b1;
    end else begin
        sin_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1496_10_fu_491_p2 = ($signed(add_ln1496_9_reg_1723) + $signed(17'd130817));

assign add_ln1496_11_fu_496_p2 = (add_ln1496_10_fu_491_p2 + select_ln1496_16_fu_484_p3);

assign add_ln1496_12_fu_731_p2 = ($signed(add_ln1496_11_reg_1739) + $signed(17'd130945));

assign add_ln1496_13_fu_736_p2 = (add_ln1496_12_fu_731_p2 + select_ln1496_19_fu_724_p3);

assign add_ln1496_14_fu_891_p2 = ($signed(add_ln1496_13_reg_1777) + $signed(17'd131009));

assign add_ln1496_15_fu_896_p2 = (add_ln1496_14_fu_891_p2 + select_ln1496_22_fu_884_p3);

assign add_ln1496_16_fu_1051_p2 = ($signed(add_ln1496_15_reg_1815) + $signed(17'd131041));

assign add_ln1496_17_fu_1056_p2 = (add_ln1496_16_fu_1051_p2 + select_ln1496_25_fu_1044_p3);

assign add_ln1496_18_fu_1211_p2 = ($signed(add_ln1496_17_reg_1853) + $signed(17'd131057));

assign add_ln1496_19_fu_1216_p2 = (add_ln1496_18_fu_1211_p2 + select_ln1496_28_fu_1204_p3);

assign add_ln1496_1_fu_326_p2 = (add_ln1496_fu_321_p2 + select_ln1496_1_fu_314_p3);

assign add_ln1496_20_fu_1351_p2 = ($signed(add_ln1496_19_reg_1891) + $signed(17'd131064));

assign add_ln1496_21_fu_1356_p2 = (add_ln1496_20_fu_1351_p2 + select_ln1496_31_fu_1344_p3);

assign add_ln1496_22_fu_1445_p2 = ($signed(add_ln1496_21_reg_1919) + $signed(17'd131069));

assign add_ln1496_23_fu_1450_p2 = (add_ln1496_22_fu_1445_p2 + select_ln1496_34_fu_1438_p3);

assign add_ln1496_24_fu_1568_p2 = ($signed(add_ln1496_23_reg_1945) + $signed(17'd131070));

assign add_ln1496_25_fu_1573_p2 = (add_ln1496_24_fu_1568_p2 + select_ln1496_37_reg_1962);

assign add_ln1496_2_fu_355_p2 = ($signed(add_ln1496_1_reg_1659) + $signed(17'd127059));

assign add_ln1496_3_fu_360_p2 = (add_ln1496_2_fu_355_p2 + select_ln1496_4_fu_348_p3);

assign add_ln1496_4_fu_389_p2 = ($signed(add_ln1496_3_reg_1675) + $signed(17'd129035));

assign add_ln1496_5_fu_394_p2 = (add_ln1496_4_fu_389_p2 + select_ln1496_7_fu_382_p3);

assign add_ln1496_6_fu_423_p2 = ($signed(add_ln1496_5_reg_1691) + $signed(17'd130050));

assign add_ln1496_7_fu_428_p2 = (add_ln1496_6_fu_423_p2 + select_ln1496_10_fu_416_p3);

assign add_ln1496_8_fu_457_p2 = ($signed(add_ln1496_7_reg_1707) + $signed(17'd130561));

assign add_ln1496_9_fu_462_p2 = (add_ln1496_8_fu_457_p2 + select_ln1496_13_fu_450_p3);

assign add_ln1496_fu_321_p2 = ($signed(add_ln68_reg_1643) + $signed(17'd123476));

assign add_ln68_fu_292_p2 = (alpha_V_2_fu_238_p3 + select_ln68_fu_284_p3);

assign add_ln703_10_fu_1249_p2 = ($signed(select_ln1496_24_reg_1875) + $signed(sext_ln1333_15_fu_1241_p1));

assign add_ln703_11_fu_774_p2 = ($signed(select_ln1496_5_reg_1755) + $signed(sext_ln1333_2_fu_758_p1));

assign add_ln703_12_fu_1409_p2 = ($signed(select_ln1496_30_reg_1913) + $signed(sext_ln1333_19_fu_1401_p1));

assign add_ln703_13_fu_1498_p2 = ($signed(select_ln1496_33_fu_1431_p3) + $signed(sext_ln1333_21_fu_1488_p1));

assign add_ln703_14_fu_1597_p2 = ($signed(select_ln1496_36_reg_1956) + $signed(sext_ln1333_23_fu_1589_p1));

assign add_ln703_15_fu_838_p2 = ($signed(select_ln1496_8_fu_784_p3) + $signed(sext_ln1333_4_fu_808_p1));

assign add_ln703_16_fu_934_p2 = ($signed(select_ln1496_11_reg_1793) + $signed(sext_ln1333_6_fu_918_p1));

assign add_ln703_17_fu_998_p2 = ($signed(select_ln1496_14_fu_944_p3) + $signed(sext_ln1333_8_fu_968_p1));

assign add_ln703_18_fu_1094_p2 = ($signed(select_ln1496_17_reg_1831) + $signed(sext_ln1333_10_fu_1078_p1));

assign add_ln703_19_fu_1158_p2 = ($signed(select_ln1496_20_fu_1104_p3) + $signed(sext_ln1333_12_fu_1128_p1));

assign add_ln703_1_fu_608_p2 = ($signed(zext_ln1496_fu_553_p1) + $signed(sext_ln1333_fu_578_p1));

assign add_ln703_20_fu_1254_p2 = ($signed(select_ln1496_23_reg_1869) + $signed(sext_ln1333_14_fu_1238_p1));

assign add_ln703_21_fu_1312_p2 = ($signed(select_ln1496_27_fu_1271_p3) + $signed(sext_ln1333_17_fu_1302_p1));

assign add_ln703_22_fu_1318_p2 = ($signed(select_ln1496_26_fu_1264_p3) + $signed(sext_ln1333_16_fu_1288_p1));

assign add_ln703_23_fu_1414_p2 = ($signed(select_ln1496_29_reg_1907) + $signed(sext_ln1333_18_fu_1398_p1));

assign add_ln703_24_fu_1504_p2 = ($signed(select_ln1496_32_fu_1424_p3) + $signed(sext_ln1333_20_fu_1474_p1));

assign add_ln703_25_fu_1602_p2 = ($signed(select_ln1496_35_reg_1950) + $signed(sext_ln1333_22_fu_1586_p1));

assign add_ln703_2_fu_672_p2 = (select_ln1496_3_fu_631_p3 + zext_ln1333_1_fu_662_p1);

assign add_ln703_3_fu_678_p2 = ($signed(zext_ln1496_1_fu_627_p1) + $signed(sext_ln1333_1_fu_648_p1));

assign add_ln703_4_fu_769_p2 = ($signed(select_ln1496_6_reg_1761) + $signed(sext_ln1333_3_fu_761_p1));

assign add_ln703_5_fu_832_p2 = ($signed(select_ln1496_9_fu_791_p3) + $signed(sext_ln1333_5_fu_822_p1));

assign add_ln703_6_fu_929_p2 = ($signed(select_ln1496_12_reg_1799) + $signed(sext_ln1333_7_fu_921_p1));

assign add_ln703_7_fu_992_p2 = ($signed(select_ln1496_15_fu_951_p3) + $signed(sext_ln1333_9_fu_982_p1));

assign add_ln703_8_fu_1089_p2 = ($signed(select_ln1496_18_reg_1837) + $signed(sext_ln1333_11_fu_1081_p1));

assign add_ln703_9_fu_1152_p2 = ($signed(select_ln1496_21_fu_1111_p3) + $signed(sext_ln1333_13_fu_1142_p1));

assign add_ln703_fu_602_p2 = ($signed(sext_ln1496_fu_564_p1) + $signed(zext_ln1333_fu_592_p1));

assign alpha_V_1_fu_224_p2 = ($signed(17'd79601) - $signed(full_alpha));

assign alpha_V_2_fu_238_p3 = ((icmp_ln1494_fu_206_p2[0:0] == 1'b1) ? alpha_V_fu_212_p2 : select_ln24_fu_230_p3);

assign alpha_V_fu_212_p2 = (17'd51471 - full_alpha);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign flag_V_fu_260_p3 = ((or_ln1494_fu_254_p2[0:0] == 1'b1) ? select_ln1494_1_fu_246_p3 : 2'd0);

assign grp_fu_200_p2 = (16'd0 - mycos_V_fu_1621_p3);

assign icmp_ln1494_fu_206_p2 = (($signed(full_alpha) > $signed(17'd25735)) ? 1'b1 : 1'b0);

assign icmp_ln1495_fu_218_p2 = (($signed(full_alpha) < $signed(17'd105337)) ? 1'b1 : 1'b0);

assign lshr_ln1333_1_fu_582_p4 = {{select_ln1333_fu_546_p3[13:2]}};

assign mycos_V_fu_1621_p3 = ((tmp_29_fu_1578_p3[0:0] == 1'b1) ? add_ln703_25_fu_1602_p2 : sub_ln703_28_fu_1592_p2);

assign or_ln1494_fu_254_p2 = (icmp_ln1495_fu_218_p2 | icmp_ln1494_fu_206_p2);

assign select_ln1333_fu_546_p3 = ((tmp_2_reg_1648_pp0_iter6_reg[0:0] == 1'b1) ? select_ln703_2_fu_532_p3 : select_ln703_fu_518_p3);

assign select_ln1494_1_fu_246_p3 = ((icmp_ln1494_fu_206_p2[0:0] == 1'b1) ? 2'd2 : 2'd3);

assign select_ln1496_10_fu_416_p3 = ((tmp_10_reg_1702[0:0] == 1'b1) ? 17'd2044 : 17'd0);

assign select_ln1496_11_fu_850_p3 = ((tmp_11_reg_1712_pp0_iter7_reg[0:0] == 1'b1) ? add_ln703_15_fu_838_p2 : sub_ln703_10_fu_826_p2);

assign select_ln1496_12_fu_857_p3 = ((tmp_11_reg_1712_pp0_iter7_reg[0:0] == 1'b1) ? sub_ln703_11_fu_844_p2 : add_ln703_5_fu_832_p2);

assign select_ln1496_13_fu_450_p3 = ((tmp_12_reg_1718[0:0] == 1'b1) ? 17'd1022 : 17'd0);

assign select_ln1496_14_fu_944_p3 = ((tmp_13_reg_1728_pp0_iter8_reg[0:0] == 1'b1) ? add_ln703_16_fu_934_p2 : sub_ln703_12_fu_924_p2);

assign select_ln1496_15_fu_951_p3 = ((tmp_13_reg_1728_pp0_iter8_reg[0:0] == 1'b1) ? sub_ln703_13_fu_939_p2 : add_ln703_6_fu_929_p2);

assign select_ln1496_16_fu_484_p3 = ((tmp_14_reg_1734[0:0] == 1'b1) ? 17'd510 : 17'd0);

assign select_ln1496_17_fu_1010_p3 = ((tmp_15_reg_1744_pp0_iter8_reg[0:0] == 1'b1) ? add_ln703_17_fu_998_p2 : sub_ln703_14_fu_986_p2);

assign select_ln1496_18_fu_1017_p3 = ((tmp_15_reg_1744_pp0_iter8_reg[0:0] == 1'b1) ? sub_ln703_15_fu_1004_p2 : add_ln703_7_fu_992_p2);

assign select_ln1496_19_fu_724_p3 = ((tmp_16_reg_1750[0:0] == 1'b1) ? 17'd254 : 17'd0);

assign select_ln1496_1_fu_314_p3 = ((tmp_3_reg_1654[0:0] == 1'b1) ? 17'd15192 : 17'd0);

assign select_ln1496_20_fu_1104_p3 = ((tmp_17_reg_1782_pp0_iter9_reg[0:0] == 1'b1) ? add_ln703_18_fu_1094_p2 : sub_ln703_16_fu_1084_p2);

assign select_ln1496_21_fu_1111_p3 = ((tmp_17_reg_1782_pp0_iter9_reg[0:0] == 1'b1) ? sub_ln703_17_fu_1099_p2 : add_ln703_8_fu_1089_p2);

assign select_ln1496_22_fu_884_p3 = ((tmp_18_reg_1788[0:0] == 1'b1) ? 17'd126 : 17'd0);

assign select_ln1496_23_fu_1170_p3 = ((tmp_19_reg_1820_pp0_iter9_reg[0:0] == 1'b1) ? add_ln703_19_fu_1158_p2 : sub_ln703_18_fu_1146_p2);

assign select_ln1496_24_fu_1177_p3 = ((tmp_19_reg_1820_pp0_iter9_reg[0:0] == 1'b1) ? sub_ln703_19_fu_1164_p2 : add_ln703_9_fu_1152_p2);

assign select_ln1496_25_fu_1044_p3 = ((tmp_20_reg_1826[0:0] == 1'b1) ? 17'd62 : 17'd0);

assign select_ln1496_26_fu_1264_p3 = ((tmp_21_reg_1858_pp0_iter10_reg[0:0] == 1'b1) ? add_ln703_20_fu_1254_p2 : sub_ln703_20_fu_1244_p2);

assign select_ln1496_27_fu_1271_p3 = ((tmp_21_reg_1858_pp0_iter10_reg[0:0] == 1'b1) ? sub_ln703_21_fu_1259_p2 : add_ln703_10_fu_1249_p2);

assign select_ln1496_28_fu_1204_p3 = ((tmp_22_reg_1864[0:0] == 1'b1) ? 17'd30 : 17'd0);

assign select_ln1496_29_fu_1330_p3 = ((tmp_23_reg_1896[0:0] == 1'b1) ? add_ln703_22_fu_1318_p2 : sub_ln703_22_fu_1306_p2);

assign select_ln1496_2_fu_620_p3 = ((tmp_4_reg_1664_pp0_iter6_reg[0:0] == 1'b1) ? add_ln703_1_fu_608_p2 : sub_ln703_4_fu_596_p2);

assign select_ln1496_30_fu_1337_p3 = ((tmp_23_reg_1896[0:0] == 1'b1) ? sub_ln703_23_fu_1324_p2 : add_ln703_21_fu_1312_p2);

assign select_ln1496_31_fu_1344_p3 = ((tmp_24_reg_1902[0:0] == 1'b1) ? 17'd16 : 17'd0);

assign select_ln1496_32_fu_1424_p3 = ((tmp_25_reg_1924[0:0] == 1'b1) ? add_ln703_23_fu_1414_p2 : sub_ln703_24_fu_1404_p2);

assign select_ln1496_33_fu_1431_p3 = ((tmp_25_reg_1924[0:0] == 1'b1) ? sub_ln703_25_fu_1419_p2 : add_ln703_12_fu_1409_p2);

assign select_ln1496_34_fu_1438_p3 = ((tmp_26_reg_1940[0:0] == 1'b1) ? 17'd6 : 17'd0);

assign select_ln1496_35_fu_1516_p3 = ((tmp_27_fu_1456_p3[0:0] == 1'b1) ? add_ln703_24_fu_1504_p2 : sub_ln703_26_fu_1492_p2);

assign select_ln1496_36_fu_1524_p3 = ((tmp_27_fu_1456_p3[0:0] == 1'b1) ? sub_ln703_27_fu_1510_p2 : add_ln703_13_fu_1498_p2);

assign select_ln1496_37_fu_1540_p3 = ((tmp_28_fu_1532_p3[0:0] == 1'b1) ? 17'd4 : 17'd0);

assign select_ln1496_3_fu_631_p3 = ((tmp_4_reg_1664_pp0_iter6_reg[0:0] == 1'b1) ? sub_ln703_5_fu_614_p2 : add_ln703_fu_602_p2);

assign select_ln1496_4_fu_348_p3 = ((tmp_5_reg_1670[0:0] == 1'b1) ? 17'd8026 : 17'd0);

assign select_ln1496_5_fu_690_p3 = ((tmp_6_reg_1680_pp0_iter6_reg[0:0] == 1'b1) ? add_ln703_3_fu_678_p2 : sub_ln703_6_fu_666_p2);

assign select_ln1496_6_fu_697_p3 = ((tmp_6_reg_1680_pp0_iter6_reg[0:0] == 1'b1) ? sub_ln703_7_fu_684_p2 : add_ln703_2_fu_672_p2);

assign select_ln1496_7_fu_382_p3 = ((tmp_8_reg_1686[0:0] == 1'b1) ? 17'd4074 : 17'd0);

assign select_ln1496_8_fu_784_p3 = ((tmp_9_reg_1696_pp0_iter7_reg[0:0] == 1'b1) ? add_ln703_11_fu_774_p2 : sub_ln703_8_fu_764_p2);

assign select_ln1496_9_fu_791_p3 = ((tmp_9_reg_1696_pp0_iter7_reg[0:0] == 1'b1) ? sub_ln703_9_fu_779_p2 : add_ln703_4_fu_769_p2);

assign select_ln1496_fu_557_p3 = ((tmp_2_reg_1648_pp0_iter6_reg[0:0] == 1'b1) ? select_ln703_3_fu_539_p3 : select_ln703_1_fu_525_p3);

assign select_ln24_fu_230_p3 = ((icmp_ln1495_fu_218_p2[0:0] == 1'b1) ? alpha_V_1_fu_224_p2 : full_alpha);

assign select_ln68_fu_284_p3 = ((tmp_1_fu_276_p3[0:0] == 1'b1) ? 17'd12867 : 17'd118205);

assign select_ln703_1_fu_525_p3 = ((tmp_reg_1635_pp0_iter6_reg[0:0] == 1'b1) ? 15'd27793 : 15'd14923);

assign select_ln703_2_fu_532_p3 = ((tmp_reg_1635_pp0_iter6_reg[0:0] == 1'b1) ? 14'd4974 : 14'd14923);

assign select_ln703_3_fu_539_p3 = ((tmp_reg_1635_pp0_iter6_reg[0:0] == 1'b1) ? 15'd17845 : 15'd4975);

assign select_ln703_fu_518_p3 = ((tmp_reg_1635_pp0_iter6_reg[0:0] == 1'b1) ? 14'd14924 : 14'd4975);

assign sext_ln1333_10_fu_1078_p1 = $signed(trunc_ln1333_2_reg_1843);

assign sext_ln1333_11_fu_1081_p1 = $signed(trunc_ln1333_10_reg_1848);

assign sext_ln1333_12_fu_1128_p1 = $signed(trunc_ln1333_11_fu_1118_p4);

assign sext_ln1333_13_fu_1142_p1 = $signed(trunc_ln1333_12_fu_1132_p4);

assign sext_ln1333_14_fu_1238_p1 = $signed(trunc_ln1333_13_reg_1881);

assign sext_ln1333_15_fu_1241_p1 = $signed(trunc_ln1333_14_reg_1886);

assign sext_ln1333_16_fu_1288_p1 = $signed(trunc_ln1333_15_fu_1278_p4);

assign sext_ln1333_17_fu_1302_p1 = $signed(trunc_ln1333_16_fu_1292_p4);

assign sext_ln1333_18_fu_1398_p1 = $signed(trunc_ln1333_17_reg_1930);

assign sext_ln1333_19_fu_1401_p1 = $signed(trunc_ln1333_18_reg_1935);

assign sext_ln1333_1_fu_648_p1 = $signed(trunc_ln1333_1_fu_638_p4);

assign sext_ln1333_20_fu_1474_p1 = $signed(trunc_ln1333_19_fu_1464_p4);

assign sext_ln1333_21_fu_1488_p1 = $signed(trunc_ln1333_20_fu_1478_p4);

assign sext_ln1333_22_fu_1586_p1 = $signed(trunc_ln1333_21_reg_1967);

assign sext_ln1333_23_fu_1589_p1 = $signed(trunc_ln1333_22_reg_1972);

assign sext_ln1333_2_fu_758_p1 = $signed(trunc_ln1333_3_reg_1767);

assign sext_ln1333_3_fu_761_p1 = $signed(trunc_ln1333_4_reg_1772);

assign sext_ln1333_4_fu_808_p1 = $signed(trunc_ln1333_5_fu_798_p4);

assign sext_ln1333_5_fu_822_p1 = $signed(trunc_ln1333_6_fu_812_p4);

assign sext_ln1333_6_fu_918_p1 = $signed(trunc_ln1333_7_reg_1805);

assign sext_ln1333_7_fu_921_p1 = $signed(trunc_ln1333_8_reg_1810);

assign sext_ln1333_8_fu_968_p1 = $signed(trunc_ln1333_9_fu_958_p4);

assign sext_ln1333_9_fu_982_p1 = $signed(trunc_ln1333_s_fu_972_p4);

assign sext_ln1333_fu_578_p1 = $signed(trunc_ln2_fu_568_p4);

assign sext_ln1496_fu_564_p1 = select_ln1496_fu_557_p3;

assign sin_out = ((tmp_29_fu_1578_p3[0:0] == 1'b1) ? sub_ln703_29_fu_1607_p2 : add_ln703_14_fu_1597_p2);

assign sub_ln703_10_fu_826_p2 = ($signed(select_ln1496_8_fu_784_p3) - $signed(sext_ln1333_4_fu_808_p1));

assign sub_ln703_11_fu_844_p2 = ($signed(select_ln1496_9_fu_791_p3) - $signed(sext_ln1333_5_fu_822_p1));

assign sub_ln703_12_fu_924_p2 = ($signed(select_ln1496_11_reg_1793) - $signed(sext_ln1333_6_fu_918_p1));

assign sub_ln703_13_fu_939_p2 = ($signed(select_ln1496_12_reg_1799) - $signed(sext_ln1333_7_fu_921_p1));

assign sub_ln703_14_fu_986_p2 = ($signed(select_ln1496_14_fu_944_p3) - $signed(sext_ln1333_8_fu_968_p1));

assign sub_ln703_15_fu_1004_p2 = ($signed(select_ln1496_15_fu_951_p3) - $signed(sext_ln1333_9_fu_982_p1));

assign sub_ln703_16_fu_1084_p2 = ($signed(select_ln1496_17_reg_1831) - $signed(sext_ln1333_10_fu_1078_p1));

assign sub_ln703_17_fu_1099_p2 = ($signed(select_ln1496_18_reg_1837) - $signed(sext_ln1333_11_fu_1081_p1));

assign sub_ln703_18_fu_1146_p2 = ($signed(select_ln1496_20_fu_1104_p3) - $signed(sext_ln1333_12_fu_1128_p1));

assign sub_ln703_19_fu_1164_p2 = ($signed(select_ln1496_21_fu_1111_p3) - $signed(sext_ln1333_13_fu_1142_p1));

assign sub_ln703_20_fu_1244_p2 = ($signed(select_ln1496_23_reg_1869) - $signed(sext_ln1333_14_fu_1238_p1));

assign sub_ln703_21_fu_1259_p2 = ($signed(select_ln1496_24_reg_1875) - $signed(sext_ln1333_15_fu_1241_p1));

assign sub_ln703_22_fu_1306_p2 = ($signed(select_ln1496_26_fu_1264_p3) - $signed(sext_ln1333_16_fu_1288_p1));

assign sub_ln703_23_fu_1324_p2 = ($signed(select_ln1496_27_fu_1271_p3) - $signed(sext_ln1333_17_fu_1302_p1));

assign sub_ln703_24_fu_1404_p2 = ($signed(select_ln1496_29_reg_1907) - $signed(sext_ln1333_18_fu_1398_p1));

assign sub_ln703_25_fu_1419_p2 = ($signed(select_ln1496_30_reg_1913) - $signed(sext_ln1333_19_fu_1401_p1));

assign sub_ln703_26_fu_1492_p2 = ($signed(select_ln1496_32_fu_1424_p3) - $signed(sext_ln1333_20_fu_1474_p1));

assign sub_ln703_27_fu_1510_p2 = ($signed(select_ln1496_33_fu_1431_p3) - $signed(sext_ln1333_21_fu_1488_p1));

assign sub_ln703_28_fu_1592_p2 = ($signed(select_ln1496_35_reg_1950) - $signed(sext_ln1333_22_fu_1586_p1));

assign sub_ln703_29_fu_1607_p2 = ($signed(select_ln1496_36_reg_1956) - $signed(sext_ln1333_23_fu_1589_p1));

assign sub_ln703_4_fu_596_p2 = ($signed(zext_ln1496_fu_553_p1) - $signed(sext_ln1333_fu_578_p1));

assign sub_ln703_5_fu_614_p2 = ($signed(sext_ln1496_fu_564_p1) - $signed(zext_ln1333_fu_592_p1));

assign sub_ln703_6_fu_666_p2 = ($signed(zext_ln1496_1_fu_627_p1) - $signed(sext_ln1333_1_fu_648_p1));

assign sub_ln703_7_fu_684_p2 = (select_ln1496_3_fu_631_p3 - zext_ln1333_1_fu_662_p1);

assign sub_ln703_8_fu_764_p2 = ($signed(select_ln1496_5_reg_1755) - $signed(sext_ln1333_2_fu_758_p1));

assign sub_ln703_9_fu_779_p2 = ($signed(select_ln1496_6_reg_1761) - $signed(sext_ln1333_3_fu_761_p1));

assign tmp_1_fu_276_p3 = alpha_V_2_fu_238_p3[32'd16];

assign tmp_27_fu_1456_p3 = add_ln1496_23_fu_1450_p2[32'd16];

assign tmp_28_fu_1532_p3 = add_ln1496_23_fu_1450_p2[32'd16];

assign tmp_29_fu_1578_p3 = add_ln1496_25_fu_1573_p2[32'd16];

assign tmp_7_fu_652_p4 = {{select_ln1496_2_fu_620_p3[14:3]}};

assign trunc_ln1333_11_fu_1118_p4 = {{select_ln1496_21_fu_1111_p3[15:9]}};

assign trunc_ln1333_12_fu_1132_p4 = {{select_ln1496_20_fu_1104_p3[15:9]}};

assign trunc_ln1333_15_fu_1278_p4 = {{select_ln1496_27_fu_1271_p3[15:11]}};

assign trunc_ln1333_16_fu_1292_p4 = {{select_ln1496_26_fu_1264_p3[15:11]}};

assign trunc_ln1333_19_fu_1464_p4 = {{select_ln1496_33_fu_1431_p3[15:13]}};

assign trunc_ln1333_1_fu_638_p4 = {{select_ln1496_3_fu_631_p3[15:3]}};

assign trunc_ln1333_20_fu_1478_p4 = {{select_ln1496_32_fu_1424_p3[15:13]}};

assign trunc_ln1333_5_fu_798_p4 = {{select_ln1496_9_fu_791_p3[15:5]}};

assign trunc_ln1333_6_fu_812_p4 = {{select_ln1496_8_fu_784_p3[15:5]}};

assign trunc_ln1333_9_fu_958_p4 = {{select_ln1496_15_fu_951_p3[15:7]}};

assign trunc_ln1333_s_fu_972_p4 = {{select_ln1496_14_fu_944_p3[15:7]}};

assign trunc_ln2_fu_568_p4 = {{select_ln1496_fu_557_p3[14:2]}};

assign zext_ln1333_1_fu_662_p1 = tmp_7_fu_652_p4;

assign zext_ln1333_fu_592_p1 = lshr_ln1333_1_fu_582_p4;

assign zext_ln1496_1_fu_627_p1 = select_ln1496_2_fu_620_p3;

assign zext_ln1496_fu_553_p1 = select_ln1333_fu_546_p3;

always @ (posedge ap_clk) begin
    select_ln1496_37_reg_1962[1:0] <= 2'b00;
    select_ln1496_37_reg_1962[16:3] <= 14'b00000000000000;
end

endmodule //cordic
