-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cordic_cordic_calculate is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    alpha : IN STD_LOGIC_VECTOR (16 downto 0);
    flag_delay_V_write : IN STD_LOGIC_VECTOR (1 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of cordic_cordic_calculate is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_3243 : STD_LOGIC_VECTOR (16 downto 0) := "00011001001000011";
    constant ap_const_lv17_1CDBD : STD_LOGIC_VECTOR (16 downto 0) := "11100110110111101";
    constant ap_const_lv17_3B58 : STD_LOGIC_VECTOR (16 downto 0) := "00011101101011000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv17_1E254 : STD_LOGIC_VECTOR (16 downto 0) := "11110001001010100";
    constant ap_const_lv17_1F5A : STD_LOGIC_VECTOR (16 downto 0) := "00001111101011010";
    constant ap_const_lv17_1F053 : STD_LOGIC_VECTOR (16 downto 0) := "11111000001010011";
    constant ap_const_lv17_FEA : STD_LOGIC_VECTOR (16 downto 0) := "00000111111101010";
    constant ap_const_lv17_1F80B : STD_LOGIC_VECTOR (16 downto 0) := "11111100000001011";
    constant ap_const_lv17_7FC : STD_LOGIC_VECTOR (16 downto 0) := "00000011111111100";
    constant ap_const_lv17_1FC02 : STD_LOGIC_VECTOR (16 downto 0) := "11111110000000010";
    constant ap_const_lv17_3FE : STD_LOGIC_VECTOR (16 downto 0) := "00000001111111110";
    constant ap_const_lv17_1FE01 : STD_LOGIC_VECTOR (16 downto 0) := "11111111000000001";
    constant ap_const_lv17_1FE : STD_LOGIC_VECTOR (16 downto 0) := "00000000111111110";
    constant ap_const_lv17_1FF01 : STD_LOGIC_VECTOR (16 downto 0) := "11111111100000001";
    constant ap_const_lv14_3A4C : STD_LOGIC_VECTOR (13 downto 0) := "11101001001100";
    constant ap_const_lv14_136F : STD_LOGIC_VECTOR (13 downto 0) := "01001101101111";
    constant ap_const_lv15_6C91 : STD_LOGIC_VECTOR (14 downto 0) := "110110010010001";
    constant ap_const_lv15_3A4B : STD_LOGIC_VECTOR (14 downto 0) := "011101001001011";
    constant ap_const_lv14_136E : STD_LOGIC_VECTOR (13 downto 0) := "01001101101110";
    constant ap_const_lv14_3A4B : STD_LOGIC_VECTOR (13 downto 0) := "11101001001011";
    constant ap_const_lv15_45B5 : STD_LOGIC_VECTOR (14 downto 0) := "100010110110101";
    constant ap_const_lv15_136F : STD_LOGIC_VECTOR (14 downto 0) := "001001101101111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv17_FE : STD_LOGIC_VECTOR (16 downto 0) := "00000000011111110";
    constant ap_const_lv17_1FF81 : STD_LOGIC_VECTOR (16 downto 0) := "11111111110000001";
    constant ap_const_lv17_7E : STD_LOGIC_VECTOR (16 downto 0) := "00000000001111110";
    constant ap_const_lv17_1FFC1 : STD_LOGIC_VECTOR (16 downto 0) := "11111111111000001";
    constant ap_const_lv17_3E : STD_LOGIC_VECTOR (16 downto 0) := "00000000000111110";
    constant ap_const_lv17_1FFE1 : STD_LOGIC_VECTOR (16 downto 0) := "11111111111100001";
    constant ap_const_lv17_1E : STD_LOGIC_VECTOR (16 downto 0) := "00000000000011110";
    constant ap_const_lv17_1FFF1 : STD_LOGIC_VECTOR (16 downto 0) := "11111111111110001";
    constant ap_const_lv17_10 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_const_lv17_1FFF8 : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111000";
    constant ap_const_lv17_6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000110";
    constant ap_const_lv17_1FFFD : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111101";
    constant ap_const_lv17_4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_const_lv17_1FFFE : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111110";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_reg_1538 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1546 : STD_LOGIC_VECTOR (0 downto 0);
    signal zi_V_fu_218_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_reg_1552 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_4_reg_1557 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1563 : STD_LOGIC_VECTOR (0 downto 0);
    signal zi_V_1_fu_252_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_1_reg_1568 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_6_reg_1573 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_1579 : STD_LOGIC_VECTOR (0 downto 0);
    signal zi_V_2_fu_286_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_2_reg_1584 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_9_reg_1589 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1595 : STD_LOGIC_VECTOR (0 downto 0);
    signal zi_V_3_fu_320_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_3_reg_1600 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_11_reg_1605 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1611 : STD_LOGIC_VECTOR (0 downto 0);
    signal zi_V_4_fu_354_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_4_reg_1616 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_13_reg_1621 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_reg_1627 : STD_LOGIC_VECTOR (0 downto 0);
    signal zi_V_5_fu_388_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_5_reg_1632 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_15_reg_1637 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_1643 : STD_LOGIC_VECTOR (0 downto 0);
    signal yi_V_8_fu_582_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_8_reg_1648 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal xi_V_8_fu_589_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_8_reg_1654 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_2_reg_1660 : STD_LOGIC_VECTOR (11 downto 0);
    signal r_3_reg_1665 : STD_LOGIC_VECTOR (11 downto 0);
    signal zi_V_6_fu_628_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_6_reg_1670 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_17_reg_1675 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_reg_1681 : STD_LOGIC_VECTOR (0 downto 0);
    signal yi_V_14_fu_742_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_14_reg_1686 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal xi_V_14_fu_749_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_14_reg_1692 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_6_reg_1698 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_7_reg_1703 : STD_LOGIC_VECTOR (9 downto 0);
    signal zi_V_7_fu_788_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_7_reg_1708 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_19_reg_1713 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_reg_1719 : STD_LOGIC_VECTOR (0 downto 0);
    signal yi_V_20_fu_902_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_20_reg_1724 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal xi_V_20_fu_909_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_20_reg_1730 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_10_reg_1736 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_11_reg_1741 : STD_LOGIC_VECTOR (7 downto 0);
    signal zi_V_8_fu_948_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_8_reg_1746 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_21_reg_1751 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_1757 : STD_LOGIC_VECTOR (0 downto 0);
    signal yi_V_26_fu_1062_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_26_reg_1762 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal xi_V_26_fu_1069_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_26_reg_1768 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_14_reg_1774 : STD_LOGIC_VECTOR (5 downto 0);
    signal r_15_reg_1779 : STD_LOGIC_VECTOR (5 downto 0);
    signal zi_V_9_fu_1108_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_9_reg_1784 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_23_reg_1789 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_reg_1795 : STD_LOGIC_VECTOR (0 downto 0);
    signal zi_V_10_fu_1234_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_10_reg_1800 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal yi_V_32_fu_1240_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_32_reg_1805 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_32_fu_1247_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_32_reg_1811 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_25_reg_1817 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_18_reg_1823 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_19_reg_1828 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_26_reg_1833 : STD_LOGIC_VECTOR (0 downto 0);
    signal zi_V_11_fu_1328_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_11_reg_1838 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal tmp_28_reg_1843 : STD_LOGIC_VECTOR (0 downto 0);
    signal yi_V_38_fu_1416_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_38_reg_1848 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_38_fu_1424_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_38_reg_1854 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_22_reg_1860 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_23_reg_1865 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal tmp_1_fu_166_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln68_fu_174_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln68_fu_182_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_3_fu_196_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1496_fu_212_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_fu_204_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_2_fu_247_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_2_fu_240_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_4_fu_281_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_5_fu_274_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_6_fu_315_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_8_fu_308_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_8_fu_349_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_11_fu_342_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_10_fu_383_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_14_fu_376_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal yi_V_1_fu_431_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal yi_V_fu_417_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal yi_V_2_fu_438_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal xi_V_1_fu_424_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal xi_V_fu_410_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal xi_V_2_fu_449_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln2_fu_460_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_fu_474_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln49_fu_456_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln1333_fu_470_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln50_fu_445_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1333_fu_484_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_4_fu_506_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_3_fu_494_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_4_fu_500_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal xi_V_3_fu_488_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal xi_V_5_fu_519_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal yi_V_5_fu_512_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_1_fu_530_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_7_fu_544_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln49_1_fu_526_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_1_fu_540_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1333_1_fu_554_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_7_fu_576_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_6_fu_564_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_7_fu_570_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_6_fu_558_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_12_fu_623_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_17_fu_616_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_2_fu_650_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_3_fu_653_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_10_fu_671_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_9_fu_661_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_10_fu_666_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_9_fu_656_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_11_fu_676_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_4_fu_690_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal xi_V_11_fu_683_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_5_fu_704_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1333_4_fu_700_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_5_fu_714_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_13_fu_736_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_12_fu_724_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_13_fu_730_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_12_fu_718_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_14_fu_783_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_20_fu_776_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_6_fu_810_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_7_fu_813_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_16_fu_831_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_15_fu_821_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_16_fu_826_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_15_fu_816_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_17_fu_836_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_8_fu_850_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal xi_V_17_fu_843_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_9_fu_864_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1333_8_fu_860_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_9_fu_874_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_19_fu_896_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_18_fu_884_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_19_fu_890_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_18_fu_878_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_16_fu_943_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_23_fu_936_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_10_fu_970_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_11_fu_973_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_22_fu_991_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_21_fu_981_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_22_fu_986_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_21_fu_976_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_23_fu_996_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_12_fu_1010_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal xi_V_23_fu_1003_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_13_fu_1024_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln1333_12_fu_1020_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_13_fu_1034_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_25_fu_1056_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_24_fu_1044_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_25_fu_1050_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_24_fu_1038_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_18_fu_1103_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_26_fu_1096_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_14_fu_1130_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_15_fu_1133_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_28_fu_1151_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_27_fu_1141_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_28_fu_1146_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_27_fu_1136_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_29_fu_1156_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_16_fu_1170_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal xi_V_29_fu_1163_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_17_fu_1184_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln1333_16_fu_1180_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_17_fu_1194_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_20_fu_1229_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_29_fu_1222_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal yi_V_31_fu_1216_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_30_fu_1204_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_31_fu_1210_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_30_fu_1198_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_18_fu_1290_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_19_fu_1293_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_22_fu_1323_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_32_fu_1316_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal yi_V_34_fu_1311_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_33_fu_1301_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_34_fu_1306_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_33_fu_1296_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_35_fu_1334_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_20_fu_1356_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal xi_V_35_fu_1341_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_21_fu_1370_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln1333_20_fu_1366_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_21_fu_1380_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_27_fu_1348_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal yi_V_37_fu_1402_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_36_fu_1390_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_37_fu_1396_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_36_fu_1384_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_24_fu_1459_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_35_fu_1452_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zi_V_12_fu_1464_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_22_fu_1478_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_23_fu_1481_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_29_fu_1470_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal yi_V_40_fu_1499_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_39_fu_1489_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_40_fu_1494_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_39_fu_1484_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal yi_V_41_fu_1504_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xi_V_41_fu_1512_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv16_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    ap_return_0_preg <= yi_V_41_fu_1504_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv16_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    ap_return_1_preg <= xi_V_41_fu_1512_p3;
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv2_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    ap_return_2_preg <= flag_delay_V_write;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                r_10_reg_1736 <= yi_V_20_fu_902_p3(15 downto 8);
                r_11_reg_1741 <= xi_V_20_fu_909_p3(15 downto 8);
                tmp_21_reg_1751 <= zi_V_8_fu_948_p2(16 downto 16);
                tmp_22_reg_1757 <= zi_V_8_fu_948_p2(16 downto 16);
                xi_V_20_reg_1730 <= xi_V_20_fu_909_p3;
                yi_V_20_reg_1724 <= yi_V_20_fu_902_p3;
                zi_V_8_reg_1746 <= zi_V_8_fu_948_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                r_14_reg_1774 <= yi_V_26_fu_1062_p3(15 downto 10);
                r_15_reg_1779 <= xi_V_26_fu_1069_p3(15 downto 10);
                tmp_23_reg_1789 <= zi_V_9_fu_1108_p2(16 downto 16);
                tmp_24_reg_1795 <= zi_V_9_fu_1108_p2(16 downto 16);
                xi_V_26_reg_1768 <= xi_V_26_fu_1069_p3;
                yi_V_26_reg_1762 <= yi_V_26_fu_1062_p3;
                zi_V_9_reg_1784 <= zi_V_9_fu_1108_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                r_18_reg_1823 <= yi_V_32_fu_1240_p3(15 downto 12);
                r_19_reg_1828 <= xi_V_32_fu_1247_p3(15 downto 12);
                tmp_25_reg_1817 <= zi_V_10_fu_1234_p2(16 downto 16);
                tmp_26_reg_1833 <= zi_V_10_fu_1234_p2(16 downto 16);
                xi_V_32_reg_1811 <= xi_V_32_fu_1247_p3;
                yi_V_32_reg_1805 <= yi_V_32_fu_1240_p3;
                zi_V_10_reg_1800 <= zi_V_10_fu_1234_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                r_22_reg_1860 <= yi_V_38_fu_1416_p3(15 downto 14);
                r_23_reg_1865 <= xi_V_38_fu_1424_p3(15 downto 14);
                tmp_28_reg_1843 <= zi_V_11_fu_1328_p2(16 downto 16);
                xi_V_38_reg_1854 <= xi_V_38_fu_1424_p3;
                yi_V_38_reg_1848 <= yi_V_38_fu_1416_p3;
                zi_V_11_reg_1838 <= zi_V_11_fu_1328_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                r_2_reg_1660 <= yi_V_8_fu_582_p3(15 downto 4);
                r_3_reg_1665 <= xi_V_8_fu_589_p3(15 downto 4);
                tmp_17_reg_1675 <= zi_V_6_fu_628_p2(16 downto 16);
                tmp_18_reg_1681 <= zi_V_6_fu_628_p2(16 downto 16);
                xi_V_8_reg_1654 <= xi_V_8_fu_589_p3;
                yi_V_8_reg_1648 <= yi_V_8_fu_582_p3;
                zi_V_6_reg_1670 <= zi_V_6_fu_628_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                r_6_reg_1698 <= yi_V_14_fu_742_p3(15 downto 6);
                r_7_reg_1703 <= xi_V_14_fu_749_p3(15 downto 6);
                tmp_19_reg_1713 <= zi_V_7_fu_788_p2(16 downto 16);
                tmp_20_reg_1719 <= zi_V_7_fu_788_p2(16 downto 16);
                xi_V_14_reg_1692 <= xi_V_14_fu_749_p3;
                yi_V_14_reg_1686 <= yi_V_14_fu_742_p3;
                zi_V_7_reg_1708 <= zi_V_7_fu_788_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                tmp_10_reg_1595 <= zi_V_2_fu_286_p2(16 downto 16);
                tmp_9_reg_1589 <= zi_V_2_fu_286_p2(16 downto 16);
                zi_V_2_reg_1584 <= zi_V_2_fu_286_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_11_reg_1605 <= zi_V_3_fu_320_p2(16 downto 16);
                tmp_12_reg_1611 <= zi_V_3_fu_320_p2(16 downto 16);
                zi_V_3_reg_1600 <= zi_V_3_fu_320_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                tmp_13_reg_1621 <= zi_V_4_fu_354_p2(16 downto 16);
                tmp_14_reg_1627 <= zi_V_4_fu_354_p2(16 downto 16);
                zi_V_4_reg_1616 <= zi_V_4_fu_354_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                tmp_15_reg_1637 <= zi_V_5_fu_388_p2(16 downto 16);
                tmp_16_reg_1643 <= zi_V_5_fu_388_p2(16 downto 16);
                zi_V_5_reg_1632 <= zi_V_5_fu_388_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                tmp_2_reg_1546 <= add_ln68_fu_182_p2(16 downto 16);
                tmp_4_reg_1557 <= zi_V_fu_218_p2(16 downto 16);
                tmp_5_reg_1563 <= zi_V_fu_218_p2(16 downto 16);
                tmp_reg_1538 <= alpha(16 downto 16);
                zi_V_reg_1552 <= zi_V_fu_218_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_6_reg_1573 <= zi_V_1_fu_252_p2(16 downto 16);
                tmp_8_reg_1579 <= zi_V_1_fu_252_p2(16 downto 16);
                zi_V_1_reg_1568 <= zi_V_1_fu_252_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    add_ln1496_10_fu_383_p2 <= std_logic_vector(unsigned(zi_V_4_reg_1616) + unsigned(ap_const_lv17_1FF01));
    add_ln1496_12_fu_623_p2 <= std_logic_vector(unsigned(zi_V_5_reg_1632) + unsigned(ap_const_lv17_1FF81));
    add_ln1496_14_fu_783_p2 <= std_logic_vector(unsigned(zi_V_6_reg_1670) + unsigned(ap_const_lv17_1FFC1));
    add_ln1496_16_fu_943_p2 <= std_logic_vector(unsigned(zi_V_7_reg_1708) + unsigned(ap_const_lv17_1FFE1));
    add_ln1496_18_fu_1103_p2 <= std_logic_vector(unsigned(zi_V_8_reg_1746) + unsigned(ap_const_lv17_1FFF1));
    add_ln1496_20_fu_1229_p2 <= std_logic_vector(unsigned(zi_V_9_reg_1784) + unsigned(ap_const_lv17_1FFF8));
    add_ln1496_22_fu_1323_p2 <= std_logic_vector(unsigned(zi_V_10_reg_1800) + unsigned(ap_const_lv17_1FFFD));
    add_ln1496_24_fu_1459_p2 <= std_logic_vector(unsigned(zi_V_11_reg_1838) + unsigned(ap_const_lv17_1FFFE));
    add_ln1496_2_fu_247_p2 <= std_logic_vector(unsigned(zi_V_reg_1552) + unsigned(ap_const_lv17_1F053));
    add_ln1496_4_fu_281_p2 <= std_logic_vector(unsigned(zi_V_1_reg_1568) + unsigned(ap_const_lv17_1F80B));
    add_ln1496_6_fu_315_p2 <= std_logic_vector(unsigned(zi_V_2_reg_1584) + unsigned(ap_const_lv17_1FC02));
    add_ln1496_8_fu_349_p2 <= std_logic_vector(unsigned(zi_V_3_reg_1600) + unsigned(ap_const_lv17_1FE01));
    add_ln1496_fu_212_p2 <= std_logic_vector(unsigned(add_ln68_fu_182_p2) + unsigned(ap_const_lv17_1E254));
    add_ln68_fu_182_p2 <= std_logic_vector(unsigned(select_ln68_fu_174_p3) + unsigned(alpha));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_CS_fsm_state13, yi_V_41_fu_1504_p3, ap_return_0_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_return_0 <= yi_V_41_fu_1504_p3;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_state13, xi_V_41_fu_1512_p3, ap_return_1_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_return_1 <= xi_V_41_fu_1512_p3;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(flag_delay_V_write, ap_CS_fsm_state13, ap_return_2_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_return_2 <= flag_delay_V_write;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;

    r_12_fu_1010_p4 <= yi_V_23_fu_996_p3(15 downto 9);
    r_13_fu_1024_p4 <= xi_V_23_fu_1003_p3(15 downto 9);
    r_16_fu_1170_p4 <= yi_V_29_fu_1156_p3(15 downto 11);
    r_17_fu_1184_p4 <= xi_V_29_fu_1163_p3(15 downto 11);
    r_1_fu_530_p4 <= yi_V_5_fu_512_p3(15 downto 3);
    r_20_fu_1356_p4 <= yi_V_35_fu_1334_p3(15 downto 13);
    r_21_fu_1370_p4 <= xi_V_35_fu_1341_p3(15 downto 13);
    r_4_fu_690_p4 <= yi_V_11_fu_676_p3(15 downto 5);
    r_5_fu_704_p4 <= xi_V_11_fu_683_p3(15 downto 5);
    r_8_fu_850_p4 <= yi_V_17_fu_836_p3(15 downto 7);
    r_9_fu_864_p4 <= xi_V_17_fu_843_p3(15 downto 7);
    r_fu_474_p4 <= xi_V_2_fu_449_p3(13 downto 2);
    select_ln1496_11_fu_342_p3 <= 
        ap_const_lv17_3FE when (tmp_12_reg_1611(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_14_fu_376_p3 <= 
        ap_const_lv17_1FE when (tmp_14_reg_1627(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_17_fu_616_p3 <= 
        ap_const_lv17_FE when (tmp_16_reg_1643(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_20_fu_776_p3 <= 
        ap_const_lv17_7E when (tmp_18_reg_1681(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_23_fu_936_p3 <= 
        ap_const_lv17_3E when (tmp_20_reg_1719(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_26_fu_1096_p3 <= 
        ap_const_lv17_1E when (tmp_22_reg_1757(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_29_fu_1222_p3 <= 
        ap_const_lv17_10 when (tmp_24_reg_1795(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_2_fu_240_p3 <= 
        ap_const_lv17_1F5A when (tmp_5_reg_1563(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_32_fu_1316_p3 <= 
        ap_const_lv17_6 when (tmp_26_reg_1833(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_35_fu_1452_p3 <= 
        ap_const_lv17_4 when (tmp_28_reg_1843(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_5_fu_274_p3 <= 
        ap_const_lv17_FEA when (tmp_8_reg_1579(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_8_fu_308_p3 <= 
        ap_const_lv17_7FC when (tmp_10_reg_1595(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_fu_204_p3 <= 
        ap_const_lv17_3B58 when (tmp_3_fu_196_p3(0) = '1') else 
        ap_const_lv17_0;
    select_ln68_fu_174_p3 <= 
        ap_const_lv17_3243 when (tmp_1_fu_166_p3(0) = '1') else 
        ap_const_lv17_1CDBD;
        sext_ln1333_10_fu_970_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_10_reg_1736),16));

        sext_ln1333_11_fu_973_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_11_reg_1741),16));

        sext_ln1333_12_fu_1020_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_12_fu_1010_p4),16));

        sext_ln1333_13_fu_1034_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_13_fu_1024_p4),16));

        sext_ln1333_14_fu_1130_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_14_reg_1774),16));

        sext_ln1333_15_fu_1133_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_15_reg_1779),16));

        sext_ln1333_16_fu_1180_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_16_fu_1170_p4),16));

        sext_ln1333_17_fu_1194_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_17_fu_1184_p4),16));

        sext_ln1333_18_fu_1290_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_18_reg_1823),16));

        sext_ln1333_19_fu_1293_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_19_reg_1828),16));

        sext_ln1333_1_fu_540_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_1_fu_530_p4),16));

        sext_ln1333_20_fu_1366_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_20_fu_1356_p4),16));

        sext_ln1333_21_fu_1380_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_21_fu_1370_p4),16));

        sext_ln1333_22_fu_1478_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_22_reg_1860),16));

        sext_ln1333_23_fu_1481_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_23_reg_1865),16));

        sext_ln1333_2_fu_650_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_2_reg_1660),16));

        sext_ln1333_3_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_3_reg_1665),16));

        sext_ln1333_4_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_4_fu_690_p4),16));

        sext_ln1333_5_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_5_fu_704_p4),16));

        sext_ln1333_6_fu_810_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_6_reg_1698),16));

        sext_ln1333_7_fu_813_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_7_reg_1703),16));

        sext_ln1333_8_fu_860_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_8_fu_850_p4),16));

        sext_ln1333_9_fu_874_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_9_fu_864_p4),16));

        sext_ln1333_fu_470_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_fu_460_p4),15));

        sext_ln50_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(yi_V_2_fu_438_p3),16));

    tmp_1_fu_166_p3 <= alpha(16 downto 16);
    tmp_27_fu_1348_p3 <= zi_V_11_fu_1328_p2(16 downto 16);
    tmp_29_fu_1470_p3 <= zi_V_12_fu_1464_p2(16 downto 16);
    tmp_3_fu_196_p3 <= add_ln68_fu_182_p2(16 downto 16);
    tmp_7_fu_544_p4 <= xi_V_5_fu_519_p3(14 downto 3);
    trunc_ln2_fu_460_p4 <= yi_V_2_fu_438_p3(14 downto 2);
    xi_V_10_fu_666_p2 <= std_logic_vector(unsigned(xi_V_8_reg_1654) + unsigned(sext_ln1333_2_fu_650_p1));
    xi_V_11_fu_683_p3 <= 
        xi_V_10_fu_666_p2 when (tmp_9_reg_1589(0) = '1') else 
        xi_V_9_fu_656_p2;
    xi_V_12_fu_718_p2 <= std_logic_vector(unsigned(xi_V_11_fu_683_p3) - unsigned(sext_ln1333_4_fu_700_p1));
    xi_V_13_fu_730_p2 <= std_logic_vector(unsigned(xi_V_11_fu_683_p3) + unsigned(sext_ln1333_4_fu_700_p1));
    xi_V_14_fu_749_p3 <= 
        xi_V_13_fu_730_p2 when (tmp_11_reg_1605(0) = '1') else 
        xi_V_12_fu_718_p2;
    xi_V_15_fu_816_p2 <= std_logic_vector(unsigned(xi_V_14_reg_1692) - unsigned(sext_ln1333_6_fu_810_p1));
    xi_V_16_fu_826_p2 <= std_logic_vector(unsigned(xi_V_14_reg_1692) + unsigned(sext_ln1333_6_fu_810_p1));
    xi_V_17_fu_843_p3 <= 
        xi_V_16_fu_826_p2 when (tmp_13_reg_1621(0) = '1') else 
        xi_V_15_fu_816_p2;
    xi_V_18_fu_878_p2 <= std_logic_vector(unsigned(xi_V_17_fu_843_p3) - unsigned(sext_ln1333_8_fu_860_p1));
    xi_V_19_fu_890_p2 <= std_logic_vector(unsigned(xi_V_17_fu_843_p3) + unsigned(sext_ln1333_8_fu_860_p1));
    xi_V_1_fu_424_p3 <= 
        ap_const_lv14_136E when (tmp_reg_1538(0) = '1') else 
        ap_const_lv14_3A4B;
    xi_V_20_fu_909_p3 <= 
        xi_V_19_fu_890_p2 when (tmp_15_reg_1637(0) = '1') else 
        xi_V_18_fu_878_p2;
    xi_V_21_fu_976_p2 <= std_logic_vector(unsigned(xi_V_20_reg_1730) - unsigned(sext_ln1333_10_fu_970_p1));
    xi_V_22_fu_986_p2 <= std_logic_vector(unsigned(xi_V_20_reg_1730) + unsigned(sext_ln1333_10_fu_970_p1));
    xi_V_23_fu_1003_p3 <= 
        xi_V_22_fu_986_p2 when (tmp_17_reg_1675(0) = '1') else 
        xi_V_21_fu_976_p2;
    xi_V_24_fu_1038_p2 <= std_logic_vector(unsigned(xi_V_23_fu_1003_p3) - unsigned(sext_ln1333_12_fu_1020_p1));
    xi_V_25_fu_1050_p2 <= std_logic_vector(unsigned(xi_V_23_fu_1003_p3) + unsigned(sext_ln1333_12_fu_1020_p1));
    xi_V_26_fu_1069_p3 <= 
        xi_V_25_fu_1050_p2 when (tmp_19_reg_1713(0) = '1') else 
        xi_V_24_fu_1038_p2;
    xi_V_27_fu_1136_p2 <= std_logic_vector(unsigned(xi_V_26_reg_1768) - unsigned(sext_ln1333_14_fu_1130_p1));
    xi_V_28_fu_1146_p2 <= std_logic_vector(unsigned(xi_V_26_reg_1768) + unsigned(sext_ln1333_14_fu_1130_p1));
    xi_V_29_fu_1163_p3 <= 
        xi_V_28_fu_1146_p2 when (tmp_21_reg_1751(0) = '1') else 
        xi_V_27_fu_1136_p2;
    xi_V_2_fu_449_p3 <= 
        xi_V_1_fu_424_p3 when (tmp_2_reg_1546(0) = '1') else 
        xi_V_fu_410_p3;
    xi_V_30_fu_1198_p2 <= std_logic_vector(unsigned(xi_V_29_fu_1163_p3) - unsigned(sext_ln1333_16_fu_1180_p1));
    xi_V_31_fu_1210_p2 <= std_logic_vector(unsigned(xi_V_29_fu_1163_p3) + unsigned(sext_ln1333_16_fu_1180_p1));
    xi_V_32_fu_1247_p3 <= 
        xi_V_31_fu_1210_p2 when (tmp_23_reg_1789(0) = '1') else 
        xi_V_30_fu_1198_p2;
    xi_V_33_fu_1296_p2 <= std_logic_vector(unsigned(xi_V_32_reg_1811) - unsigned(sext_ln1333_18_fu_1290_p1));
    xi_V_34_fu_1306_p2 <= std_logic_vector(unsigned(xi_V_32_reg_1811) + unsigned(sext_ln1333_18_fu_1290_p1));
    xi_V_35_fu_1341_p3 <= 
        xi_V_34_fu_1306_p2 when (tmp_25_reg_1817(0) = '1') else 
        xi_V_33_fu_1296_p2;
    xi_V_36_fu_1384_p2 <= std_logic_vector(unsigned(xi_V_35_fu_1341_p3) - unsigned(sext_ln1333_20_fu_1366_p1));
    xi_V_37_fu_1396_p2 <= std_logic_vector(unsigned(xi_V_35_fu_1341_p3) + unsigned(sext_ln1333_20_fu_1366_p1));
    xi_V_38_fu_1424_p3 <= 
        xi_V_37_fu_1396_p2 when (tmp_27_fu_1348_p3(0) = '1') else 
        xi_V_36_fu_1384_p2;
    xi_V_39_fu_1484_p2 <= std_logic_vector(unsigned(xi_V_38_reg_1854) - unsigned(sext_ln1333_22_fu_1478_p1));
    xi_V_3_fu_488_p2 <= std_logic_vector(unsigned(zext_ln49_fu_456_p1) - unsigned(sext_ln1333_fu_470_p1));
    xi_V_40_fu_1494_p2 <= std_logic_vector(unsigned(xi_V_38_reg_1854) + unsigned(sext_ln1333_22_fu_1478_p1));
    xi_V_41_fu_1512_p3 <= 
        xi_V_40_fu_1494_p2 when (tmp_29_fu_1470_p3(0) = '1') else 
        xi_V_39_fu_1484_p2;
    xi_V_4_fu_500_p2 <= std_logic_vector(unsigned(zext_ln49_fu_456_p1) + unsigned(sext_ln1333_fu_470_p1));
    xi_V_5_fu_519_p3 <= 
        xi_V_4_fu_500_p2 when (tmp_4_reg_1557(0) = '1') else 
        xi_V_3_fu_488_p2;
    xi_V_6_fu_558_p2 <= std_logic_vector(unsigned(zext_ln49_1_fu_526_p1) - unsigned(sext_ln1333_1_fu_540_p1));
    xi_V_7_fu_570_p2 <= std_logic_vector(unsigned(zext_ln49_1_fu_526_p1) + unsigned(sext_ln1333_1_fu_540_p1));
    xi_V_8_fu_589_p3 <= 
        xi_V_7_fu_570_p2 when (tmp_6_reg_1573(0) = '1') else 
        xi_V_6_fu_558_p2;
    xi_V_9_fu_656_p2 <= std_logic_vector(unsigned(xi_V_8_reg_1654) - unsigned(sext_ln1333_2_fu_650_p1));
    xi_V_fu_410_p3 <= 
        ap_const_lv14_3A4C when (tmp_reg_1538(0) = '1') else 
        ap_const_lv14_136F;
    yi_V_10_fu_671_p2 <= std_logic_vector(unsigned(yi_V_8_reg_1648) - unsigned(sext_ln1333_3_fu_653_p1));
    yi_V_11_fu_676_p3 <= 
        yi_V_10_fu_671_p2 when (tmp_9_reg_1589(0) = '1') else 
        yi_V_9_fu_661_p2;
    yi_V_12_fu_724_p2 <= std_logic_vector(unsigned(yi_V_11_fu_676_p3) + unsigned(sext_ln1333_5_fu_714_p1));
    yi_V_13_fu_736_p2 <= std_logic_vector(unsigned(yi_V_11_fu_676_p3) - unsigned(sext_ln1333_5_fu_714_p1));
    yi_V_14_fu_742_p3 <= 
        yi_V_13_fu_736_p2 when (tmp_11_reg_1605(0) = '1') else 
        yi_V_12_fu_724_p2;
    yi_V_15_fu_821_p2 <= std_logic_vector(unsigned(yi_V_14_reg_1686) + unsigned(sext_ln1333_7_fu_813_p1));
    yi_V_16_fu_831_p2 <= std_logic_vector(unsigned(yi_V_14_reg_1686) - unsigned(sext_ln1333_7_fu_813_p1));
    yi_V_17_fu_836_p3 <= 
        yi_V_16_fu_831_p2 when (tmp_13_reg_1621(0) = '1') else 
        yi_V_15_fu_821_p2;
    yi_V_18_fu_884_p2 <= std_logic_vector(unsigned(yi_V_17_fu_836_p3) + unsigned(sext_ln1333_9_fu_874_p1));
    yi_V_19_fu_896_p2 <= std_logic_vector(unsigned(yi_V_17_fu_836_p3) - unsigned(sext_ln1333_9_fu_874_p1));
    yi_V_1_fu_431_p3 <= 
        ap_const_lv15_45B5 when (tmp_reg_1538(0) = '1') else 
        ap_const_lv15_136F;
    yi_V_20_fu_902_p3 <= 
        yi_V_19_fu_896_p2 when (tmp_15_reg_1637(0) = '1') else 
        yi_V_18_fu_884_p2;
    yi_V_21_fu_981_p2 <= std_logic_vector(unsigned(yi_V_20_reg_1724) + unsigned(sext_ln1333_11_fu_973_p1));
    yi_V_22_fu_991_p2 <= std_logic_vector(unsigned(yi_V_20_reg_1724) - unsigned(sext_ln1333_11_fu_973_p1));
    yi_V_23_fu_996_p3 <= 
        yi_V_22_fu_991_p2 when (tmp_17_reg_1675(0) = '1') else 
        yi_V_21_fu_981_p2;
    yi_V_24_fu_1044_p2 <= std_logic_vector(unsigned(yi_V_23_fu_996_p3) + unsigned(sext_ln1333_13_fu_1034_p1));
    yi_V_25_fu_1056_p2 <= std_logic_vector(unsigned(yi_V_23_fu_996_p3) - unsigned(sext_ln1333_13_fu_1034_p1));
    yi_V_26_fu_1062_p3 <= 
        yi_V_25_fu_1056_p2 when (tmp_19_reg_1713(0) = '1') else 
        yi_V_24_fu_1044_p2;
    yi_V_27_fu_1141_p2 <= std_logic_vector(unsigned(yi_V_26_reg_1762) + unsigned(sext_ln1333_15_fu_1133_p1));
    yi_V_28_fu_1151_p2 <= std_logic_vector(unsigned(yi_V_26_reg_1762) - unsigned(sext_ln1333_15_fu_1133_p1));
    yi_V_29_fu_1156_p3 <= 
        yi_V_28_fu_1151_p2 when (tmp_21_reg_1751(0) = '1') else 
        yi_V_27_fu_1141_p2;
    yi_V_2_fu_438_p3 <= 
        yi_V_1_fu_431_p3 when (tmp_2_reg_1546(0) = '1') else 
        yi_V_fu_417_p3;
    yi_V_30_fu_1204_p2 <= std_logic_vector(unsigned(yi_V_29_fu_1156_p3) + unsigned(sext_ln1333_17_fu_1194_p1));
    yi_V_31_fu_1216_p2 <= std_logic_vector(unsigned(yi_V_29_fu_1156_p3) - unsigned(sext_ln1333_17_fu_1194_p1));
    yi_V_32_fu_1240_p3 <= 
        yi_V_31_fu_1216_p2 when (tmp_23_reg_1789(0) = '1') else 
        yi_V_30_fu_1204_p2;
    yi_V_33_fu_1301_p2 <= std_logic_vector(unsigned(yi_V_32_reg_1805) + unsigned(sext_ln1333_19_fu_1293_p1));
    yi_V_34_fu_1311_p2 <= std_logic_vector(unsigned(yi_V_32_reg_1805) - unsigned(sext_ln1333_19_fu_1293_p1));
    yi_V_35_fu_1334_p3 <= 
        yi_V_34_fu_1311_p2 when (tmp_25_reg_1817(0) = '1') else 
        yi_V_33_fu_1301_p2;
    yi_V_36_fu_1390_p2 <= std_logic_vector(unsigned(yi_V_35_fu_1334_p3) + unsigned(sext_ln1333_21_fu_1380_p1));
    yi_V_37_fu_1402_p2 <= std_logic_vector(unsigned(yi_V_35_fu_1334_p3) - unsigned(sext_ln1333_21_fu_1380_p1));
    yi_V_38_fu_1416_p3 <= 
        yi_V_37_fu_1402_p2 when (tmp_27_fu_1348_p3(0) = '1') else 
        yi_V_36_fu_1390_p2;
    yi_V_39_fu_1489_p2 <= std_logic_vector(unsigned(yi_V_38_reg_1848) + unsigned(sext_ln1333_23_fu_1481_p1));
    yi_V_3_fu_494_p2 <= std_logic_vector(signed(sext_ln50_fu_445_p1) + signed(zext_ln1333_fu_484_p1));
    yi_V_40_fu_1499_p2 <= std_logic_vector(unsigned(yi_V_38_reg_1848) - unsigned(sext_ln1333_23_fu_1481_p1));
    yi_V_41_fu_1504_p3 <= 
        yi_V_40_fu_1499_p2 when (tmp_29_fu_1470_p3(0) = '1') else 
        yi_V_39_fu_1489_p2;
    yi_V_4_fu_506_p2 <= std_logic_vector(signed(sext_ln50_fu_445_p1) - signed(zext_ln1333_fu_484_p1));
    yi_V_5_fu_512_p3 <= 
        yi_V_4_fu_506_p2 when (tmp_4_reg_1557(0) = '1') else 
        yi_V_3_fu_494_p2;
    yi_V_6_fu_564_p2 <= std_logic_vector(unsigned(yi_V_5_fu_512_p3) + unsigned(zext_ln1333_1_fu_554_p1));
    yi_V_7_fu_576_p2 <= std_logic_vector(unsigned(yi_V_5_fu_512_p3) - unsigned(zext_ln1333_1_fu_554_p1));
    yi_V_8_fu_582_p3 <= 
        yi_V_7_fu_576_p2 when (tmp_6_reg_1573(0) = '1') else 
        yi_V_6_fu_564_p2;
    yi_V_9_fu_661_p2 <= std_logic_vector(unsigned(yi_V_8_reg_1648) + unsigned(sext_ln1333_3_fu_653_p1));
    yi_V_fu_417_p3 <= 
        ap_const_lv15_6C91 when (tmp_reg_1538(0) = '1') else 
        ap_const_lv15_3A4B;
    zext_ln1333_1_fu_554_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_544_p4),16));
    zext_ln1333_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_474_p4),16));
    zext_ln49_1_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xi_V_5_fu_519_p3),16));
    zext_ln49_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xi_V_2_fu_449_p3),15));
    zi_V_10_fu_1234_p2 <= std_logic_vector(unsigned(add_ln1496_20_fu_1229_p2) + unsigned(select_ln1496_29_fu_1222_p3));
    zi_V_11_fu_1328_p2 <= std_logic_vector(unsigned(add_ln1496_22_fu_1323_p2) + unsigned(select_ln1496_32_fu_1316_p3));
    zi_V_12_fu_1464_p2 <= std_logic_vector(unsigned(add_ln1496_24_fu_1459_p2) + unsigned(select_ln1496_35_fu_1452_p3));
    zi_V_1_fu_252_p2 <= std_logic_vector(unsigned(add_ln1496_2_fu_247_p2) + unsigned(select_ln1496_2_fu_240_p3));
    zi_V_2_fu_286_p2 <= std_logic_vector(unsigned(add_ln1496_4_fu_281_p2) + unsigned(select_ln1496_5_fu_274_p3));
    zi_V_3_fu_320_p2 <= std_logic_vector(unsigned(add_ln1496_6_fu_315_p2) + unsigned(select_ln1496_8_fu_308_p3));
    zi_V_4_fu_354_p2 <= std_logic_vector(unsigned(add_ln1496_8_fu_349_p2) + unsigned(select_ln1496_11_fu_342_p3));
    zi_V_5_fu_388_p2 <= std_logic_vector(unsigned(add_ln1496_10_fu_383_p2) + unsigned(select_ln1496_14_fu_376_p3));
    zi_V_6_fu_628_p2 <= std_logic_vector(unsigned(add_ln1496_12_fu_623_p2) + unsigned(select_ln1496_17_fu_616_p3));
    zi_V_7_fu_788_p2 <= std_logic_vector(unsigned(add_ln1496_14_fu_783_p2) + unsigned(select_ln1496_20_fu_776_p3));
    zi_V_8_fu_948_p2 <= std_logic_vector(unsigned(add_ln1496_16_fu_943_p2) + unsigned(select_ln1496_23_fu_936_p3));
    zi_V_9_fu_1108_p2 <= std_logic_vector(unsigned(add_ln1496_18_fu_1103_p2) + unsigned(select_ln1496_26_fu_1096_p3));
    zi_V_fu_218_p2 <= std_logic_vector(unsigned(add_ln1496_fu_212_p2) + unsigned(select_ln1496_fu_204_p3));
end behav;
