-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cordic is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    full_alpha : IN STD_LOGIC_VECTOR (16 downto 0);
    sin_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    sin_out_ap_vld : OUT STD_LOGIC;
    cos_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    cos_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of cordic is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "cordic_cordic,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=6.814250,HLS_SYN_LAT=13,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1181,HLS_SYN_LUT=2750,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv17_6487 : STD_LOGIC_VECTOR (16 downto 0) := "00110010010000111";
    constant ap_const_lv17_C90F : STD_LOGIC_VECTOR (16 downto 0) := "01100100100001111";
    constant ap_const_lv17_19B79 : STD_LOGIC_VECTOR (16 downto 0) := "11001101101111001";
    constant ap_const_lv17_136F1 : STD_LOGIC_VECTOR (16 downto 0) := "10011011011110001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_3243 : STD_LOGIC_VECTOR (16 downto 0) := "00011001001000011";
    constant ap_const_lv17_1CDBD : STD_LOGIC_VECTOR (16 downto 0) := "11100110110111101";
    constant ap_const_lv17_3B58 : STD_LOGIC_VECTOR (16 downto 0) := "00011101101011000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv17_1E254 : STD_LOGIC_VECTOR (16 downto 0) := "11110001001010100";
    constant ap_const_lv17_1F5A : STD_LOGIC_VECTOR (16 downto 0) := "00001111101011010";
    constant ap_const_lv17_1F053 : STD_LOGIC_VECTOR (16 downto 0) := "11111000001010011";
    constant ap_const_lv17_FEA : STD_LOGIC_VECTOR (16 downto 0) := "00000111111101010";
    constant ap_const_lv17_1F80B : STD_LOGIC_VECTOR (16 downto 0) := "11111100000001011";
    constant ap_const_lv17_7FC : STD_LOGIC_VECTOR (16 downto 0) := "00000011111111100";
    constant ap_const_lv17_1FC02 : STD_LOGIC_VECTOR (16 downto 0) := "11111110000000010";
    constant ap_const_lv17_3FE : STD_LOGIC_VECTOR (16 downto 0) := "00000001111111110";
    constant ap_const_lv17_1FE01 : STD_LOGIC_VECTOR (16 downto 0) := "11111111000000001";
    constant ap_const_lv17_1FE : STD_LOGIC_VECTOR (16 downto 0) := "00000000111111110";
    constant ap_const_lv17_1FF01 : STD_LOGIC_VECTOR (16 downto 0) := "11111111100000001";
    constant ap_const_lv14_3A4C : STD_LOGIC_VECTOR (13 downto 0) := "11101001001100";
    constant ap_const_lv14_136F : STD_LOGIC_VECTOR (13 downto 0) := "01001101101111";
    constant ap_const_lv15_6C91 : STD_LOGIC_VECTOR (14 downto 0) := "110110010010001";
    constant ap_const_lv15_3A4B : STD_LOGIC_VECTOR (14 downto 0) := "011101001001011";
    constant ap_const_lv14_136E : STD_LOGIC_VECTOR (13 downto 0) := "01001101101110";
    constant ap_const_lv14_3A4B : STD_LOGIC_VECTOR (13 downto 0) := "11101001001011";
    constant ap_const_lv15_45B5 : STD_LOGIC_VECTOR (14 downto 0) := "100010110110101";
    constant ap_const_lv15_136F : STD_LOGIC_VECTOR (14 downto 0) := "001001101101111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv17_FE : STD_LOGIC_VECTOR (16 downto 0) := "00000000011111110";
    constant ap_const_lv17_1FF81 : STD_LOGIC_VECTOR (16 downto 0) := "11111111110000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv17_7E : STD_LOGIC_VECTOR (16 downto 0) := "00000000001111110";
    constant ap_const_lv17_1FFC1 : STD_LOGIC_VECTOR (16 downto 0) := "11111111111000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv17_3E : STD_LOGIC_VECTOR (16 downto 0) := "00000000000111110";
    constant ap_const_lv17_1FFE1 : STD_LOGIC_VECTOR (16 downto 0) := "11111111111100001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv17_1E : STD_LOGIC_VECTOR (16 downto 0) := "00000000000011110";
    constant ap_const_lv17_1FFF1 : STD_LOGIC_VECTOR (16 downto 0) := "11111111111110001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv17_10 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_const_lv17_1FFF8 : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv17_6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000110";
    constant ap_const_lv17_1FFFD : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111101";
    constant ap_const_lv17_4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_const_lv17_1FFFE : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111110";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal flag_V_fu_260_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631 : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal flag_V_reg_1631_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_reg_1635 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1635_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1635_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1635_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1635_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1635_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1635_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln68_fu_292_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln68_reg_1643 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_reg_1648 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1648_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1648_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1648_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1648_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1648_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1648_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_1654 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1496_1_fu_326_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_1_reg_1659 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_4_reg_1664 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1664_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1664_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1664_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1664_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1664_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1670 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1496_3_fu_360_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_3_reg_1675 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_6_reg_1680 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1680_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1680_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1680_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1680_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_1686 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1496_5_fu_394_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_5_reg_1691 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_9_reg_1696 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_1696_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_1696_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_1696_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_1696_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1702 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1496_7_fu_428_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_7_reg_1707 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_11_reg_1712 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_reg_1712_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_reg_1712_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_reg_1712_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1718 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1496_9_fu_462_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_9_reg_1723 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_13_reg_1728 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_1728_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_1728_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_1728_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_reg_1734 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1496_11_fu_496_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_11_reg_1739 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_15_reg_1744 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_reg_1744_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_reg_1744_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_1750 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1496_5_fu_690_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_5_reg_1755 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_6_fu_697_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_6_reg_1761 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_3_reg_1767 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln1333_4_reg_1772 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln1496_13_fu_736_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_13_reg_1777 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_17_reg_1782 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_1782_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_1782_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_reg_1788 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1496_11_fu_850_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_11_reg_1793 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_12_fu_857_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_12_reg_1799 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_7_reg_1805 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln1333_8_reg_1810 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1496_15_fu_896_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_15_reg_1815 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_19_reg_1820 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_1820_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_reg_1826 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1496_17_fu_1010_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_17_reg_1831 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_18_fu_1017_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_18_reg_1837 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_2_reg_1843 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1333_10_reg_1848 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1496_17_fu_1056_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_17_reg_1853 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_21_reg_1858 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_reg_1858_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_1864 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1496_23_fu_1170_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_23_reg_1869 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_24_fu_1177_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_24_reg_1875 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_13_reg_1881 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln1333_14_reg_1886 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln1496_19_fu_1216_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_19_reg_1891 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_23_reg_1896 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_reg_1902 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1496_29_fu_1330_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_29_reg_1907 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_30_fu_1337_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_30_reg_1913 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_21_fu_1356_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_21_reg_1919 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_25_reg_1924 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1333_17_reg_1930 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln1333_18_reg_1935 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_26_reg_1940 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1496_23_fu_1450_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_23_reg_1945 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_35_fu_1516_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_35_reg_1950 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_36_fu_1524_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_36_reg_1956 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_37_fu_1540_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_37_reg_1962 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln1333_21_reg_1967 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln1333_22_reg_1972 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_200_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mycos_V_fu_1621_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln1495_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal alpha_V_1_fu_224_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln1494_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal alpha_V_fu_212_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln24_fu_230_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal or_ln1494_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1494_1_fu_246_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal alpha_V_2_fu_238_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_1_fu_276_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln68_fu_284_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_fu_321_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_1_fu_314_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_2_fu_355_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_4_fu_348_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_4_fu_389_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_7_fu_382_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_6_fu_423_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_10_fu_416_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_8_fu_457_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_13_fu_450_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_10_fu_491_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_16_fu_484_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln703_2_fu_532_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln703_fu_518_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln1333_fu_546_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln703_3_fu_539_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln703_1_fu_525_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln1496_fu_557_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln2_fu_568_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln1333_1_fu_582_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1496_fu_553_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln1333_fu_578_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln1496_fu_564_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1333_fu_592_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_1_fu_608_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln703_4_fu_596_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln1496_2_fu_620_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln703_5_fu_614_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_fu_602_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_3_fu_631_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_1_fu_638_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_7_fu_652_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1496_1_fu_627_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_1_fu_648_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1333_1_fu_662_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_3_fu_678_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_6_fu_666_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_7_fu_684_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_2_fu_672_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_12_fu_731_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_19_fu_724_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_2_fu_758_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_3_fu_761_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_11_fu_774_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_8_fu_764_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_9_fu_779_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_4_fu_769_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_9_fu_791_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_5_fu_798_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln1496_8_fu_784_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_6_fu_812_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1333_4_fu_808_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_5_fu_822_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_15_fu_838_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_10_fu_826_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_11_fu_844_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_5_fu_832_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_14_fu_891_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_22_fu_884_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_6_fu_918_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_7_fu_921_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_16_fu_934_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_12_fu_924_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_13_fu_939_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_6_fu_929_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_15_fu_951_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_9_fu_958_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln1496_14_fu_944_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_s_fu_972_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1333_8_fu_968_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_9_fu_982_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_17_fu_998_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_14_fu_986_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_15_fu_1004_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_7_fu_992_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_16_fu_1051_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_25_fu_1044_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_10_fu_1078_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_11_fu_1081_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_18_fu_1094_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_16_fu_1084_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_17_fu_1099_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_8_fu_1089_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_21_fu_1111_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_11_fu_1118_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln1496_20_fu_1104_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_12_fu_1132_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln1333_12_fu_1128_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_13_fu_1142_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_19_fu_1158_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_18_fu_1146_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_19_fu_1164_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_9_fu_1152_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_18_fu_1211_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_28_fu_1204_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_14_fu_1238_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_15_fu_1241_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_20_fu_1254_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_20_fu_1244_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_21_fu_1259_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_10_fu_1249_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1496_27_fu_1271_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_15_fu_1278_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln1496_26_fu_1264_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_16_fu_1292_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln1333_16_fu_1288_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_17_fu_1302_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_22_fu_1318_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_22_fu_1306_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_23_fu_1324_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_21_fu_1312_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_20_fu_1351_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_31_fu_1344_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_18_fu_1398_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_19_fu_1401_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_23_fu_1414_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_24_fu_1404_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_25_fu_1419_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_12_fu_1409_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1496_22_fu_1445_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_34_fu_1438_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1496_33_fu_1431_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_19_fu_1464_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln1496_32_fu_1424_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1333_20_fu_1478_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln1333_20_fu_1474_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_21_fu_1488_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_27_fu_1456_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln703_24_fu_1504_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_26_fu_1492_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_27_fu_1510_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_13_fu_1498_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_28_fu_1532_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1496_24_fu_1568_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln1496_25_fu_1573_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1333_22_fu_1586_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1333_23_fu_1589_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_29_fu_1578_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln703_29_fu_1607_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_14_fu_1597_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_25_fu_1602_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln703_28_fu_1592_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to12 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln1496_11_reg_1739 <= add_ln1496_11_fu_496_p2;
                add_ln1496_13_reg_1777 <= add_ln1496_13_fu_736_p2;
                add_ln1496_15_reg_1815 <= add_ln1496_15_fu_896_p2;
                add_ln1496_17_reg_1853 <= add_ln1496_17_fu_1056_p2;
                add_ln1496_19_reg_1891 <= add_ln1496_19_fu_1216_p2;
                add_ln1496_21_reg_1919 <= add_ln1496_21_fu_1356_p2;
                add_ln1496_23_reg_1945 <= add_ln1496_23_fu_1450_p2;
                add_ln1496_3_reg_1675 <= add_ln1496_3_fu_360_p2;
                add_ln1496_5_reg_1691 <= add_ln1496_5_fu_394_p2;
                add_ln1496_7_reg_1707 <= add_ln1496_7_fu_428_p2;
                add_ln1496_9_reg_1723 <= add_ln1496_9_fu_462_p2;
                flag_V_reg_1631_pp0_iter10_reg <= flag_V_reg_1631_pp0_iter9_reg;
                flag_V_reg_1631_pp0_iter11_reg <= flag_V_reg_1631_pp0_iter10_reg;
                flag_V_reg_1631_pp0_iter12_reg <= flag_V_reg_1631_pp0_iter11_reg;
                flag_V_reg_1631_pp0_iter2_reg <= flag_V_reg_1631_pp0_iter1_reg;
                flag_V_reg_1631_pp0_iter3_reg <= flag_V_reg_1631_pp0_iter2_reg;
                flag_V_reg_1631_pp0_iter4_reg <= flag_V_reg_1631_pp0_iter3_reg;
                flag_V_reg_1631_pp0_iter5_reg <= flag_V_reg_1631_pp0_iter4_reg;
                flag_V_reg_1631_pp0_iter6_reg <= flag_V_reg_1631_pp0_iter5_reg;
                flag_V_reg_1631_pp0_iter7_reg <= flag_V_reg_1631_pp0_iter6_reg;
                flag_V_reg_1631_pp0_iter8_reg <= flag_V_reg_1631_pp0_iter7_reg;
                flag_V_reg_1631_pp0_iter9_reg <= flag_V_reg_1631_pp0_iter8_reg;
                select_ln1496_11_reg_1793 <= select_ln1496_11_fu_850_p3;
                select_ln1496_12_reg_1799 <= select_ln1496_12_fu_857_p3;
                select_ln1496_17_reg_1831 <= select_ln1496_17_fu_1010_p3;
                select_ln1496_18_reg_1837 <= select_ln1496_18_fu_1017_p3;
                select_ln1496_23_reg_1869 <= select_ln1496_23_fu_1170_p3;
                select_ln1496_24_reg_1875 <= select_ln1496_24_fu_1177_p3;
                select_ln1496_29_reg_1907 <= select_ln1496_29_fu_1330_p3;
                select_ln1496_30_reg_1913 <= select_ln1496_30_fu_1337_p3;
                select_ln1496_35_reg_1950 <= select_ln1496_35_fu_1516_p3;
                select_ln1496_36_reg_1956 <= select_ln1496_36_fu_1524_p3;
                    select_ln1496_37_reg_1962(2) <= select_ln1496_37_fu_1540_p3(2);
                select_ln1496_5_reg_1755 <= select_ln1496_5_fu_690_p3;
                select_ln1496_6_reg_1761 <= select_ln1496_6_fu_697_p3;
                tmp_10_reg_1702 <= add_ln1496_5_fu_394_p2(16 downto 16);
                tmp_11_reg_1712 <= add_ln1496_7_fu_428_p2(16 downto 16);
                tmp_11_reg_1712_pp0_iter5_reg <= tmp_11_reg_1712;
                tmp_11_reg_1712_pp0_iter6_reg <= tmp_11_reg_1712_pp0_iter5_reg;
                tmp_11_reg_1712_pp0_iter7_reg <= tmp_11_reg_1712_pp0_iter6_reg;
                tmp_12_reg_1718 <= add_ln1496_7_fu_428_p2(16 downto 16);
                tmp_13_reg_1728 <= add_ln1496_9_fu_462_p2(16 downto 16);
                tmp_13_reg_1728_pp0_iter6_reg <= tmp_13_reg_1728;
                tmp_13_reg_1728_pp0_iter7_reg <= tmp_13_reg_1728_pp0_iter6_reg;
                tmp_13_reg_1728_pp0_iter8_reg <= tmp_13_reg_1728_pp0_iter7_reg;
                tmp_14_reg_1734 <= add_ln1496_9_fu_462_p2(16 downto 16);
                tmp_15_reg_1744 <= add_ln1496_11_fu_496_p2(16 downto 16);
                tmp_15_reg_1744_pp0_iter7_reg <= tmp_15_reg_1744;
                tmp_15_reg_1744_pp0_iter8_reg <= tmp_15_reg_1744_pp0_iter7_reg;
                tmp_16_reg_1750 <= add_ln1496_11_fu_496_p2(16 downto 16);
                tmp_17_reg_1782 <= add_ln1496_13_fu_736_p2(16 downto 16);
                tmp_17_reg_1782_pp0_iter8_reg <= tmp_17_reg_1782;
                tmp_17_reg_1782_pp0_iter9_reg <= tmp_17_reg_1782_pp0_iter8_reg;
                tmp_18_reg_1788 <= add_ln1496_13_fu_736_p2(16 downto 16);
                tmp_19_reg_1820 <= add_ln1496_15_fu_896_p2(16 downto 16);
                tmp_19_reg_1820_pp0_iter9_reg <= tmp_19_reg_1820;
                tmp_20_reg_1826 <= add_ln1496_15_fu_896_p2(16 downto 16);
                tmp_21_reg_1858 <= add_ln1496_17_fu_1056_p2(16 downto 16);
                tmp_21_reg_1858_pp0_iter10_reg <= tmp_21_reg_1858;
                tmp_22_reg_1864 <= add_ln1496_17_fu_1056_p2(16 downto 16);
                tmp_23_reg_1896 <= add_ln1496_19_fu_1216_p2(16 downto 16);
                tmp_24_reg_1902 <= add_ln1496_19_fu_1216_p2(16 downto 16);
                tmp_25_reg_1924 <= add_ln1496_21_fu_1356_p2(16 downto 16);
                tmp_26_reg_1940 <= add_ln1496_21_fu_1356_p2(16 downto 16);
                tmp_2_reg_1648_pp0_iter2_reg <= tmp_2_reg_1648_pp0_iter1_reg;
                tmp_2_reg_1648_pp0_iter3_reg <= tmp_2_reg_1648_pp0_iter2_reg;
                tmp_2_reg_1648_pp0_iter4_reg <= tmp_2_reg_1648_pp0_iter3_reg;
                tmp_2_reg_1648_pp0_iter5_reg <= tmp_2_reg_1648_pp0_iter4_reg;
                tmp_2_reg_1648_pp0_iter6_reg <= tmp_2_reg_1648_pp0_iter5_reg;
                tmp_4_reg_1664_pp0_iter2_reg <= tmp_4_reg_1664;
                tmp_4_reg_1664_pp0_iter3_reg <= tmp_4_reg_1664_pp0_iter2_reg;
                tmp_4_reg_1664_pp0_iter4_reg <= tmp_4_reg_1664_pp0_iter3_reg;
                tmp_4_reg_1664_pp0_iter5_reg <= tmp_4_reg_1664_pp0_iter4_reg;
                tmp_4_reg_1664_pp0_iter6_reg <= tmp_4_reg_1664_pp0_iter5_reg;
                tmp_6_reg_1680 <= add_ln1496_3_fu_360_p2(16 downto 16);
                tmp_6_reg_1680_pp0_iter3_reg <= tmp_6_reg_1680;
                tmp_6_reg_1680_pp0_iter4_reg <= tmp_6_reg_1680_pp0_iter3_reg;
                tmp_6_reg_1680_pp0_iter5_reg <= tmp_6_reg_1680_pp0_iter4_reg;
                tmp_6_reg_1680_pp0_iter6_reg <= tmp_6_reg_1680_pp0_iter5_reg;
                tmp_8_reg_1686 <= add_ln1496_3_fu_360_p2(16 downto 16);
                tmp_9_reg_1696 <= add_ln1496_5_fu_394_p2(16 downto 16);
                tmp_9_reg_1696_pp0_iter4_reg <= tmp_9_reg_1696;
                tmp_9_reg_1696_pp0_iter5_reg <= tmp_9_reg_1696_pp0_iter4_reg;
                tmp_9_reg_1696_pp0_iter6_reg <= tmp_9_reg_1696_pp0_iter5_reg;
                tmp_9_reg_1696_pp0_iter7_reg <= tmp_9_reg_1696_pp0_iter6_reg;
                tmp_reg_1635_pp0_iter2_reg <= tmp_reg_1635_pp0_iter1_reg;
                tmp_reg_1635_pp0_iter3_reg <= tmp_reg_1635_pp0_iter2_reg;
                tmp_reg_1635_pp0_iter4_reg <= tmp_reg_1635_pp0_iter3_reg;
                tmp_reg_1635_pp0_iter5_reg <= tmp_reg_1635_pp0_iter4_reg;
                tmp_reg_1635_pp0_iter6_reg <= tmp_reg_1635_pp0_iter5_reg;
                trunc_ln1333_10_reg_1848 <= select_ln1496_17_fu_1010_p3(15 downto 8);
                trunc_ln1333_13_reg_1881 <= select_ln1496_24_fu_1177_p3(15 downto 10);
                trunc_ln1333_14_reg_1886 <= select_ln1496_23_fu_1170_p3(15 downto 10);
                trunc_ln1333_17_reg_1930 <= select_ln1496_30_fu_1337_p3(15 downto 12);
                trunc_ln1333_18_reg_1935 <= select_ln1496_29_fu_1330_p3(15 downto 12);
                trunc_ln1333_21_reg_1967 <= select_ln1496_36_fu_1524_p3(15 downto 14);
                trunc_ln1333_22_reg_1972 <= select_ln1496_35_fu_1516_p3(15 downto 14);
                trunc_ln1333_2_reg_1843 <= select_ln1496_18_fu_1017_p3(15 downto 8);
                trunc_ln1333_3_reg_1767 <= select_ln1496_6_fu_697_p3(15 downto 4);
                trunc_ln1333_4_reg_1772 <= select_ln1496_5_fu_690_p3(15 downto 4);
                trunc_ln1333_7_reg_1805 <= select_ln1496_12_fu_857_p3(15 downto 6);
                trunc_ln1333_8_reg_1810 <= select_ln1496_11_fu_850_p3(15 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln1496_1_reg_1659 <= add_ln1496_1_fu_326_p2;
                add_ln68_reg_1643 <= add_ln68_fu_292_p2;
                flag_V_reg_1631 <= flag_V_fu_260_p3;
                flag_V_reg_1631_pp0_iter1_reg <= flag_V_reg_1631;
                tmp_2_reg_1648 <= add_ln68_fu_292_p2(16 downto 16);
                tmp_2_reg_1648_pp0_iter1_reg <= tmp_2_reg_1648;
                tmp_3_reg_1654 <= add_ln68_fu_292_p2(16 downto 16);
                tmp_4_reg_1664 <= add_ln1496_1_fu_326_p2(16 downto 16);
                tmp_5_reg_1670 <= add_ln1496_1_fu_326_p2(16 downto 16);
                tmp_reg_1635 <= alpha_V_2_fu_238_p3(16 downto 16);
                tmp_reg_1635_pp0_iter1_reg <= tmp_reg_1635;
            end if;
        end if;
    end process;
    select_ln1496_37_reg_1962(1 downto 0) <= "00";
    select_ln1496_37_reg_1962(16 downto 3) <= "00000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1496_10_fu_491_p2 <= std_logic_vector(unsigned(add_ln1496_9_reg_1723) + unsigned(ap_const_lv17_1FF01));
    add_ln1496_11_fu_496_p2 <= std_logic_vector(unsigned(add_ln1496_10_fu_491_p2) + unsigned(select_ln1496_16_fu_484_p3));
    add_ln1496_12_fu_731_p2 <= std_logic_vector(unsigned(add_ln1496_11_reg_1739) + unsigned(ap_const_lv17_1FF81));
    add_ln1496_13_fu_736_p2 <= std_logic_vector(unsigned(add_ln1496_12_fu_731_p2) + unsigned(select_ln1496_19_fu_724_p3));
    add_ln1496_14_fu_891_p2 <= std_logic_vector(unsigned(add_ln1496_13_reg_1777) + unsigned(ap_const_lv17_1FFC1));
    add_ln1496_15_fu_896_p2 <= std_logic_vector(unsigned(add_ln1496_14_fu_891_p2) + unsigned(select_ln1496_22_fu_884_p3));
    add_ln1496_16_fu_1051_p2 <= std_logic_vector(unsigned(add_ln1496_15_reg_1815) + unsigned(ap_const_lv17_1FFE1));
    add_ln1496_17_fu_1056_p2 <= std_logic_vector(unsigned(add_ln1496_16_fu_1051_p2) + unsigned(select_ln1496_25_fu_1044_p3));
    add_ln1496_18_fu_1211_p2 <= std_logic_vector(unsigned(add_ln1496_17_reg_1853) + unsigned(ap_const_lv17_1FFF1));
    add_ln1496_19_fu_1216_p2 <= std_logic_vector(unsigned(add_ln1496_18_fu_1211_p2) + unsigned(select_ln1496_28_fu_1204_p3));
    add_ln1496_1_fu_326_p2 <= std_logic_vector(unsigned(add_ln1496_fu_321_p2) + unsigned(select_ln1496_1_fu_314_p3));
    add_ln1496_20_fu_1351_p2 <= std_logic_vector(unsigned(add_ln1496_19_reg_1891) + unsigned(ap_const_lv17_1FFF8));
    add_ln1496_21_fu_1356_p2 <= std_logic_vector(unsigned(add_ln1496_20_fu_1351_p2) + unsigned(select_ln1496_31_fu_1344_p3));
    add_ln1496_22_fu_1445_p2 <= std_logic_vector(unsigned(add_ln1496_21_reg_1919) + unsigned(ap_const_lv17_1FFFD));
    add_ln1496_23_fu_1450_p2 <= std_logic_vector(unsigned(add_ln1496_22_fu_1445_p2) + unsigned(select_ln1496_34_fu_1438_p3));
    add_ln1496_24_fu_1568_p2 <= std_logic_vector(unsigned(add_ln1496_23_reg_1945) + unsigned(ap_const_lv17_1FFFE));
    add_ln1496_25_fu_1573_p2 <= std_logic_vector(unsigned(add_ln1496_24_fu_1568_p2) + unsigned(select_ln1496_37_reg_1962));
    add_ln1496_2_fu_355_p2 <= std_logic_vector(unsigned(add_ln1496_1_reg_1659) + unsigned(ap_const_lv17_1F053));
    add_ln1496_3_fu_360_p2 <= std_logic_vector(unsigned(add_ln1496_2_fu_355_p2) + unsigned(select_ln1496_4_fu_348_p3));
    add_ln1496_4_fu_389_p2 <= std_logic_vector(unsigned(add_ln1496_3_reg_1675) + unsigned(ap_const_lv17_1F80B));
    add_ln1496_5_fu_394_p2 <= std_logic_vector(unsigned(add_ln1496_4_fu_389_p2) + unsigned(select_ln1496_7_fu_382_p3));
    add_ln1496_6_fu_423_p2 <= std_logic_vector(unsigned(add_ln1496_5_reg_1691) + unsigned(ap_const_lv17_1FC02));
    add_ln1496_7_fu_428_p2 <= std_logic_vector(unsigned(add_ln1496_6_fu_423_p2) + unsigned(select_ln1496_10_fu_416_p3));
    add_ln1496_8_fu_457_p2 <= std_logic_vector(unsigned(add_ln1496_7_reg_1707) + unsigned(ap_const_lv17_1FE01));
    add_ln1496_9_fu_462_p2 <= std_logic_vector(unsigned(add_ln1496_8_fu_457_p2) + unsigned(select_ln1496_13_fu_450_p3));
    add_ln1496_fu_321_p2 <= std_logic_vector(unsigned(add_ln68_reg_1643) + unsigned(ap_const_lv17_1E254));
    add_ln68_fu_292_p2 <= std_logic_vector(unsigned(alpha_V_2_fu_238_p3) + unsigned(select_ln68_fu_284_p3));
    add_ln703_10_fu_1249_p2 <= std_logic_vector(unsigned(select_ln1496_24_reg_1875) + unsigned(sext_ln1333_15_fu_1241_p1));
    add_ln703_11_fu_774_p2 <= std_logic_vector(unsigned(select_ln1496_5_reg_1755) + unsigned(sext_ln1333_2_fu_758_p1));
    add_ln703_12_fu_1409_p2 <= std_logic_vector(unsigned(select_ln1496_30_reg_1913) + unsigned(sext_ln1333_19_fu_1401_p1));
    add_ln703_13_fu_1498_p2 <= std_logic_vector(unsigned(select_ln1496_33_fu_1431_p3) + unsigned(sext_ln1333_21_fu_1488_p1));
    add_ln703_14_fu_1597_p2 <= std_logic_vector(unsigned(select_ln1496_36_reg_1956) + unsigned(sext_ln1333_23_fu_1589_p1));
    add_ln703_15_fu_838_p2 <= std_logic_vector(unsigned(select_ln1496_8_fu_784_p3) + unsigned(sext_ln1333_4_fu_808_p1));
    add_ln703_16_fu_934_p2 <= std_logic_vector(unsigned(select_ln1496_11_reg_1793) + unsigned(sext_ln1333_6_fu_918_p1));
    add_ln703_17_fu_998_p2 <= std_logic_vector(unsigned(select_ln1496_14_fu_944_p3) + unsigned(sext_ln1333_8_fu_968_p1));
    add_ln703_18_fu_1094_p2 <= std_logic_vector(unsigned(select_ln1496_17_reg_1831) + unsigned(sext_ln1333_10_fu_1078_p1));
    add_ln703_19_fu_1158_p2 <= std_logic_vector(unsigned(select_ln1496_20_fu_1104_p3) + unsigned(sext_ln1333_12_fu_1128_p1));
    add_ln703_1_fu_608_p2 <= std_logic_vector(unsigned(zext_ln1496_fu_553_p1) + unsigned(sext_ln1333_fu_578_p1));
    add_ln703_20_fu_1254_p2 <= std_logic_vector(unsigned(select_ln1496_23_reg_1869) + unsigned(sext_ln1333_14_fu_1238_p1));
    add_ln703_21_fu_1312_p2 <= std_logic_vector(unsigned(select_ln1496_27_fu_1271_p3) + unsigned(sext_ln1333_17_fu_1302_p1));
    add_ln703_22_fu_1318_p2 <= std_logic_vector(unsigned(select_ln1496_26_fu_1264_p3) + unsigned(sext_ln1333_16_fu_1288_p1));
    add_ln703_23_fu_1414_p2 <= std_logic_vector(unsigned(select_ln1496_29_reg_1907) + unsigned(sext_ln1333_18_fu_1398_p1));
    add_ln703_24_fu_1504_p2 <= std_logic_vector(unsigned(select_ln1496_32_fu_1424_p3) + unsigned(sext_ln1333_20_fu_1474_p1));
    add_ln703_25_fu_1602_p2 <= std_logic_vector(unsigned(select_ln1496_35_reg_1950) + unsigned(sext_ln1333_22_fu_1586_p1));
    add_ln703_2_fu_672_p2 <= std_logic_vector(unsigned(select_ln1496_3_fu_631_p3) + unsigned(zext_ln1333_1_fu_662_p1));
    add_ln703_3_fu_678_p2 <= std_logic_vector(unsigned(zext_ln1496_1_fu_627_p1) + unsigned(sext_ln1333_1_fu_648_p1));
    add_ln703_4_fu_769_p2 <= std_logic_vector(unsigned(select_ln1496_6_reg_1761) + unsigned(sext_ln1333_3_fu_761_p1));
    add_ln703_5_fu_832_p2 <= std_logic_vector(unsigned(select_ln1496_9_fu_791_p3) + unsigned(sext_ln1333_5_fu_822_p1));
    add_ln703_6_fu_929_p2 <= std_logic_vector(unsigned(select_ln1496_12_reg_1799) + unsigned(sext_ln1333_7_fu_921_p1));
    add_ln703_7_fu_992_p2 <= std_logic_vector(unsigned(select_ln1496_15_fu_951_p3) + unsigned(sext_ln1333_9_fu_982_p1));
    add_ln703_8_fu_1089_p2 <= std_logic_vector(unsigned(select_ln1496_18_reg_1837) + unsigned(sext_ln1333_11_fu_1081_p1));
    add_ln703_9_fu_1152_p2 <= std_logic_vector(unsigned(select_ln1496_21_fu_1111_p3) + unsigned(sext_ln1333_13_fu_1142_p1));
    add_ln703_fu_602_p2 <= std_logic_vector(signed(sext_ln1496_fu_564_p1) + signed(zext_ln1333_fu_592_p1));
    alpha_V_1_fu_224_p2 <= std_logic_vector(signed(ap_const_lv17_136F1) - signed(full_alpha));
    alpha_V_2_fu_238_p3 <= 
        alpha_V_fu_212_p2 when (icmp_ln1494_fu_206_p2(0) = '1') else 
        select_ln24_fu_230_p3;
    alpha_V_fu_212_p2 <= std_logic_vector(unsigned(ap_const_lv17_C90F) - unsigned(full_alpha));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to12_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to12 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to12)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to12 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    cos_out_assign_proc : process(ap_enable_reg_pp0_iter13, flag_V_reg_1631_pp0_iter12_reg, ap_block_pp0_stage0_01001, grp_fu_200_p2, mycos_V_fu_1621_p3)
    begin
        if ((not((flag_V_reg_1631_pp0_iter12_reg = ap_const_lv2_2)) and not((flag_V_reg_1631_pp0_iter12_reg = ap_const_lv2_3)) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cos_out <= mycos_V_fu_1621_p3;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (flag_V_reg_1631_pp0_iter12_reg = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (flag_V_reg_1631_pp0_iter12_reg = ap_const_lv2_3)))) then 
            cos_out <= grp_fu_200_p2;
        else 
            cos_out <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    cos_out_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, flag_V_reg_1631_pp0_iter12_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (flag_V_reg_1631_pp0_iter12_reg = ap_const_lv2_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (flag_V_reg_1631_pp0_iter12_reg = ap_const_lv2_3)) or (not((flag_V_reg_1631_pp0_iter12_reg = ap_const_lv2_2)) and not((flag_V_reg_1631_pp0_iter12_reg = ap_const_lv2_3)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1)))) then 
            cos_out_ap_vld <= ap_const_logic_1;
        else 
            cos_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    flag_V_fu_260_p3 <= 
        select_ln1494_1_fu_246_p3 when (or_ln1494_fu_254_p2(0) = '1') else 
        ap_const_lv2_0;
    grp_fu_200_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(mycos_V_fu_1621_p3));
    icmp_ln1494_fu_206_p2 <= "1" when (signed(full_alpha) > signed(ap_const_lv17_6487)) else "0";
    icmp_ln1495_fu_218_p2 <= "1" when (signed(full_alpha) < signed(ap_const_lv17_19B79)) else "0";
    lshr_ln1333_1_fu_582_p4 <= select_ln1333_fu_546_p3(13 downto 2);
    mycos_V_fu_1621_p3 <= 
        add_ln703_25_fu_1602_p2 when (tmp_29_fu_1578_p3(0) = '1') else 
        sub_ln703_28_fu_1592_p2;
    or_ln1494_fu_254_p2 <= (icmp_ln1495_fu_218_p2 or icmp_ln1494_fu_206_p2);
    select_ln1333_fu_546_p3 <= 
        select_ln703_2_fu_532_p3 when (tmp_2_reg_1648_pp0_iter6_reg(0) = '1') else 
        select_ln703_fu_518_p3;
    select_ln1494_1_fu_246_p3 <= 
        ap_const_lv2_2 when (icmp_ln1494_fu_206_p2(0) = '1') else 
        ap_const_lv2_3;
    select_ln1496_10_fu_416_p3 <= 
        ap_const_lv17_7FC when (tmp_10_reg_1702(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_11_fu_850_p3 <= 
        add_ln703_15_fu_838_p2 when (tmp_11_reg_1712_pp0_iter7_reg(0) = '1') else 
        sub_ln703_10_fu_826_p2;
    select_ln1496_12_fu_857_p3 <= 
        sub_ln703_11_fu_844_p2 when (tmp_11_reg_1712_pp0_iter7_reg(0) = '1') else 
        add_ln703_5_fu_832_p2;
    select_ln1496_13_fu_450_p3 <= 
        ap_const_lv17_3FE when (tmp_12_reg_1718(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_14_fu_944_p3 <= 
        add_ln703_16_fu_934_p2 when (tmp_13_reg_1728_pp0_iter8_reg(0) = '1') else 
        sub_ln703_12_fu_924_p2;
    select_ln1496_15_fu_951_p3 <= 
        sub_ln703_13_fu_939_p2 when (tmp_13_reg_1728_pp0_iter8_reg(0) = '1') else 
        add_ln703_6_fu_929_p2;
    select_ln1496_16_fu_484_p3 <= 
        ap_const_lv17_1FE when (tmp_14_reg_1734(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_17_fu_1010_p3 <= 
        add_ln703_17_fu_998_p2 when (tmp_15_reg_1744_pp0_iter8_reg(0) = '1') else 
        sub_ln703_14_fu_986_p2;
    select_ln1496_18_fu_1017_p3 <= 
        sub_ln703_15_fu_1004_p2 when (tmp_15_reg_1744_pp0_iter8_reg(0) = '1') else 
        add_ln703_7_fu_992_p2;
    select_ln1496_19_fu_724_p3 <= 
        ap_const_lv17_FE when (tmp_16_reg_1750(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_1_fu_314_p3 <= 
        ap_const_lv17_3B58 when (tmp_3_reg_1654(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_20_fu_1104_p3 <= 
        add_ln703_18_fu_1094_p2 when (tmp_17_reg_1782_pp0_iter9_reg(0) = '1') else 
        sub_ln703_16_fu_1084_p2;
    select_ln1496_21_fu_1111_p3 <= 
        sub_ln703_17_fu_1099_p2 when (tmp_17_reg_1782_pp0_iter9_reg(0) = '1') else 
        add_ln703_8_fu_1089_p2;
    select_ln1496_22_fu_884_p3 <= 
        ap_const_lv17_7E when (tmp_18_reg_1788(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_23_fu_1170_p3 <= 
        add_ln703_19_fu_1158_p2 when (tmp_19_reg_1820_pp0_iter9_reg(0) = '1') else 
        sub_ln703_18_fu_1146_p2;
    select_ln1496_24_fu_1177_p3 <= 
        sub_ln703_19_fu_1164_p2 when (tmp_19_reg_1820_pp0_iter9_reg(0) = '1') else 
        add_ln703_9_fu_1152_p2;
    select_ln1496_25_fu_1044_p3 <= 
        ap_const_lv17_3E when (tmp_20_reg_1826(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_26_fu_1264_p3 <= 
        add_ln703_20_fu_1254_p2 when (tmp_21_reg_1858_pp0_iter10_reg(0) = '1') else 
        sub_ln703_20_fu_1244_p2;
    select_ln1496_27_fu_1271_p3 <= 
        sub_ln703_21_fu_1259_p2 when (tmp_21_reg_1858_pp0_iter10_reg(0) = '1') else 
        add_ln703_10_fu_1249_p2;
    select_ln1496_28_fu_1204_p3 <= 
        ap_const_lv17_1E when (tmp_22_reg_1864(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_29_fu_1330_p3 <= 
        add_ln703_22_fu_1318_p2 when (tmp_23_reg_1896(0) = '1') else 
        sub_ln703_22_fu_1306_p2;
    select_ln1496_2_fu_620_p3 <= 
        add_ln703_1_fu_608_p2 when (tmp_4_reg_1664_pp0_iter6_reg(0) = '1') else 
        sub_ln703_4_fu_596_p2;
    select_ln1496_30_fu_1337_p3 <= 
        sub_ln703_23_fu_1324_p2 when (tmp_23_reg_1896(0) = '1') else 
        add_ln703_21_fu_1312_p2;
    select_ln1496_31_fu_1344_p3 <= 
        ap_const_lv17_10 when (tmp_24_reg_1902(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_32_fu_1424_p3 <= 
        add_ln703_23_fu_1414_p2 when (tmp_25_reg_1924(0) = '1') else 
        sub_ln703_24_fu_1404_p2;
    select_ln1496_33_fu_1431_p3 <= 
        sub_ln703_25_fu_1419_p2 when (tmp_25_reg_1924(0) = '1') else 
        add_ln703_12_fu_1409_p2;
    select_ln1496_34_fu_1438_p3 <= 
        ap_const_lv17_6 when (tmp_26_reg_1940(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_35_fu_1516_p3 <= 
        add_ln703_24_fu_1504_p2 when (tmp_27_fu_1456_p3(0) = '1') else 
        sub_ln703_26_fu_1492_p2;
    select_ln1496_36_fu_1524_p3 <= 
        sub_ln703_27_fu_1510_p2 when (tmp_27_fu_1456_p3(0) = '1') else 
        add_ln703_13_fu_1498_p2;
    select_ln1496_37_fu_1540_p3 <= 
        ap_const_lv17_4 when (tmp_28_fu_1532_p3(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_3_fu_631_p3 <= 
        sub_ln703_5_fu_614_p2 when (tmp_4_reg_1664_pp0_iter6_reg(0) = '1') else 
        add_ln703_fu_602_p2;
    select_ln1496_4_fu_348_p3 <= 
        ap_const_lv17_1F5A when (tmp_5_reg_1670(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_5_fu_690_p3 <= 
        add_ln703_3_fu_678_p2 when (tmp_6_reg_1680_pp0_iter6_reg(0) = '1') else 
        sub_ln703_6_fu_666_p2;
    select_ln1496_6_fu_697_p3 <= 
        sub_ln703_7_fu_684_p2 when (tmp_6_reg_1680_pp0_iter6_reg(0) = '1') else 
        add_ln703_2_fu_672_p2;
    select_ln1496_7_fu_382_p3 <= 
        ap_const_lv17_FEA when (tmp_8_reg_1686(0) = '1') else 
        ap_const_lv17_0;
    select_ln1496_8_fu_784_p3 <= 
        add_ln703_11_fu_774_p2 when (tmp_9_reg_1696_pp0_iter7_reg(0) = '1') else 
        sub_ln703_8_fu_764_p2;
    select_ln1496_9_fu_791_p3 <= 
        sub_ln703_9_fu_779_p2 when (tmp_9_reg_1696_pp0_iter7_reg(0) = '1') else 
        add_ln703_4_fu_769_p2;
    select_ln1496_fu_557_p3 <= 
        select_ln703_3_fu_539_p3 when (tmp_2_reg_1648_pp0_iter6_reg(0) = '1') else 
        select_ln703_1_fu_525_p3;
    select_ln24_fu_230_p3 <= 
        alpha_V_1_fu_224_p2 when (icmp_ln1495_fu_218_p2(0) = '1') else 
        full_alpha;
    select_ln68_fu_284_p3 <= 
        ap_const_lv17_3243 when (tmp_1_fu_276_p3(0) = '1') else 
        ap_const_lv17_1CDBD;
    select_ln703_1_fu_525_p3 <= 
        ap_const_lv15_6C91 when (tmp_reg_1635_pp0_iter6_reg(0) = '1') else 
        ap_const_lv15_3A4B;
    select_ln703_2_fu_532_p3 <= 
        ap_const_lv14_136E when (tmp_reg_1635_pp0_iter6_reg(0) = '1') else 
        ap_const_lv14_3A4B;
    select_ln703_3_fu_539_p3 <= 
        ap_const_lv15_45B5 when (tmp_reg_1635_pp0_iter6_reg(0) = '1') else 
        ap_const_lv15_136F;
    select_ln703_fu_518_p3 <= 
        ap_const_lv14_3A4C when (tmp_reg_1635_pp0_iter6_reg(0) = '1') else 
        ap_const_lv14_136F;
        sext_ln1333_10_fu_1078_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_2_reg_1843),16));

        sext_ln1333_11_fu_1081_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_10_reg_1848),16));

        sext_ln1333_12_fu_1128_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_11_fu_1118_p4),16));

        sext_ln1333_13_fu_1142_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_12_fu_1132_p4),16));

        sext_ln1333_14_fu_1238_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_13_reg_1881),16));

        sext_ln1333_15_fu_1241_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_14_reg_1886),16));

        sext_ln1333_16_fu_1288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_15_fu_1278_p4),16));

        sext_ln1333_17_fu_1302_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_16_fu_1292_p4),16));

        sext_ln1333_18_fu_1398_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_17_reg_1930),16));

        sext_ln1333_19_fu_1401_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_18_reg_1935),16));

        sext_ln1333_1_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_1_fu_638_p4),16));

        sext_ln1333_20_fu_1474_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_19_fu_1464_p4),16));

        sext_ln1333_21_fu_1488_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_20_fu_1478_p4),16));

        sext_ln1333_22_fu_1586_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_21_reg_1967),16));

        sext_ln1333_23_fu_1589_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_22_reg_1972),16));

        sext_ln1333_2_fu_758_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_3_reg_1767),16));

        sext_ln1333_3_fu_761_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_4_reg_1772),16));

        sext_ln1333_4_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_5_fu_798_p4),16));

        sext_ln1333_5_fu_822_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_6_fu_812_p4),16));

        sext_ln1333_6_fu_918_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_7_reg_1805),16));

        sext_ln1333_7_fu_921_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_8_reg_1810),16));

        sext_ln1333_8_fu_968_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_9_fu_958_p4),16));

        sext_ln1333_9_fu_982_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1333_s_fu_972_p4),16));

        sext_ln1333_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_fu_568_p4),15));

        sext_ln1496_fu_564_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln1496_fu_557_p3),16));

    sin_out <= 
        sub_ln703_29_fu_1607_p2 when (tmp_29_fu_1578_p3(0) = '1') else 
        add_ln703_14_fu_1597_p2;

    sin_out_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            sin_out_ap_vld <= ap_const_logic_1;
        else 
            sin_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln703_10_fu_826_p2 <= std_logic_vector(unsigned(select_ln1496_8_fu_784_p3) - unsigned(sext_ln1333_4_fu_808_p1));
    sub_ln703_11_fu_844_p2 <= std_logic_vector(unsigned(select_ln1496_9_fu_791_p3) - unsigned(sext_ln1333_5_fu_822_p1));
    sub_ln703_12_fu_924_p2 <= std_logic_vector(unsigned(select_ln1496_11_reg_1793) - unsigned(sext_ln1333_6_fu_918_p1));
    sub_ln703_13_fu_939_p2 <= std_logic_vector(unsigned(select_ln1496_12_reg_1799) - unsigned(sext_ln1333_7_fu_921_p1));
    sub_ln703_14_fu_986_p2 <= std_logic_vector(unsigned(select_ln1496_14_fu_944_p3) - unsigned(sext_ln1333_8_fu_968_p1));
    sub_ln703_15_fu_1004_p2 <= std_logic_vector(unsigned(select_ln1496_15_fu_951_p3) - unsigned(sext_ln1333_9_fu_982_p1));
    sub_ln703_16_fu_1084_p2 <= std_logic_vector(unsigned(select_ln1496_17_reg_1831) - unsigned(sext_ln1333_10_fu_1078_p1));
    sub_ln703_17_fu_1099_p2 <= std_logic_vector(unsigned(select_ln1496_18_reg_1837) - unsigned(sext_ln1333_11_fu_1081_p1));
    sub_ln703_18_fu_1146_p2 <= std_logic_vector(unsigned(select_ln1496_20_fu_1104_p3) - unsigned(sext_ln1333_12_fu_1128_p1));
    sub_ln703_19_fu_1164_p2 <= std_logic_vector(unsigned(select_ln1496_21_fu_1111_p3) - unsigned(sext_ln1333_13_fu_1142_p1));
    sub_ln703_20_fu_1244_p2 <= std_logic_vector(unsigned(select_ln1496_23_reg_1869) - unsigned(sext_ln1333_14_fu_1238_p1));
    sub_ln703_21_fu_1259_p2 <= std_logic_vector(unsigned(select_ln1496_24_reg_1875) - unsigned(sext_ln1333_15_fu_1241_p1));
    sub_ln703_22_fu_1306_p2 <= std_logic_vector(unsigned(select_ln1496_26_fu_1264_p3) - unsigned(sext_ln1333_16_fu_1288_p1));
    sub_ln703_23_fu_1324_p2 <= std_logic_vector(unsigned(select_ln1496_27_fu_1271_p3) - unsigned(sext_ln1333_17_fu_1302_p1));
    sub_ln703_24_fu_1404_p2 <= std_logic_vector(unsigned(select_ln1496_29_reg_1907) - unsigned(sext_ln1333_18_fu_1398_p1));
    sub_ln703_25_fu_1419_p2 <= std_logic_vector(unsigned(select_ln1496_30_reg_1913) - unsigned(sext_ln1333_19_fu_1401_p1));
    sub_ln703_26_fu_1492_p2 <= std_logic_vector(unsigned(select_ln1496_32_fu_1424_p3) - unsigned(sext_ln1333_20_fu_1474_p1));
    sub_ln703_27_fu_1510_p2 <= std_logic_vector(unsigned(select_ln1496_33_fu_1431_p3) - unsigned(sext_ln1333_21_fu_1488_p1));
    sub_ln703_28_fu_1592_p2 <= std_logic_vector(unsigned(select_ln1496_35_reg_1950) - unsigned(sext_ln1333_22_fu_1586_p1));
    sub_ln703_29_fu_1607_p2 <= std_logic_vector(unsigned(select_ln1496_36_reg_1956) - unsigned(sext_ln1333_23_fu_1589_p1));
    sub_ln703_4_fu_596_p2 <= std_logic_vector(unsigned(zext_ln1496_fu_553_p1) - unsigned(sext_ln1333_fu_578_p1));
    sub_ln703_5_fu_614_p2 <= std_logic_vector(signed(sext_ln1496_fu_564_p1) - signed(zext_ln1333_fu_592_p1));
    sub_ln703_6_fu_666_p2 <= std_logic_vector(unsigned(zext_ln1496_1_fu_627_p1) - unsigned(sext_ln1333_1_fu_648_p1));
    sub_ln703_7_fu_684_p2 <= std_logic_vector(unsigned(select_ln1496_3_fu_631_p3) - unsigned(zext_ln1333_1_fu_662_p1));
    sub_ln703_8_fu_764_p2 <= std_logic_vector(unsigned(select_ln1496_5_reg_1755) - unsigned(sext_ln1333_2_fu_758_p1));
    sub_ln703_9_fu_779_p2 <= std_logic_vector(unsigned(select_ln1496_6_reg_1761) - unsigned(sext_ln1333_3_fu_761_p1));
    tmp_1_fu_276_p3 <= alpha_V_2_fu_238_p3(16 downto 16);
    tmp_27_fu_1456_p3 <= add_ln1496_23_fu_1450_p2(16 downto 16);
    tmp_28_fu_1532_p3 <= add_ln1496_23_fu_1450_p2(16 downto 16);
    tmp_29_fu_1578_p3 <= add_ln1496_25_fu_1573_p2(16 downto 16);
    tmp_7_fu_652_p4 <= select_ln1496_2_fu_620_p3(14 downto 3);
    trunc_ln1333_11_fu_1118_p4 <= select_ln1496_21_fu_1111_p3(15 downto 9);
    trunc_ln1333_12_fu_1132_p4 <= select_ln1496_20_fu_1104_p3(15 downto 9);
    trunc_ln1333_15_fu_1278_p4 <= select_ln1496_27_fu_1271_p3(15 downto 11);
    trunc_ln1333_16_fu_1292_p4 <= select_ln1496_26_fu_1264_p3(15 downto 11);
    trunc_ln1333_19_fu_1464_p4 <= select_ln1496_33_fu_1431_p3(15 downto 13);
    trunc_ln1333_1_fu_638_p4 <= select_ln1496_3_fu_631_p3(15 downto 3);
    trunc_ln1333_20_fu_1478_p4 <= select_ln1496_32_fu_1424_p3(15 downto 13);
    trunc_ln1333_5_fu_798_p4 <= select_ln1496_9_fu_791_p3(15 downto 5);
    trunc_ln1333_6_fu_812_p4 <= select_ln1496_8_fu_784_p3(15 downto 5);
    trunc_ln1333_9_fu_958_p4 <= select_ln1496_15_fu_951_p3(15 downto 7);
    trunc_ln1333_s_fu_972_p4 <= select_ln1496_14_fu_944_p3(15 downto 7);
    trunc_ln2_fu_568_p4 <= select_ln1496_fu_557_p3(14 downto 2);
    zext_ln1333_1_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_652_p4),16));
    zext_ln1333_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1333_1_fu_582_p4),16));
    zext_ln1496_1_fu_627_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1496_2_fu_620_p3),16));
    zext_ln1496_fu_553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1333_fu_546_p3),15));
end behav;
