// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cordic_cordic_calculate (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        alpha,
        flag_delay_V_write,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [16:0] alpha;
input  [1:0] flag_delay_V_write;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [1:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[1:0] ap_return_2;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] tmp_reg_1538;
reg   [0:0] tmp_2_reg_1546;
wire   [16:0] zi_V_fu_218_p2;
reg   [16:0] zi_V_reg_1552;
reg   [0:0] tmp_4_reg_1557;
reg   [0:0] tmp_5_reg_1563;
wire   [16:0] zi_V_1_fu_252_p2;
reg   [16:0] zi_V_1_reg_1568;
wire    ap_CS_fsm_state2;
reg   [0:0] tmp_6_reg_1573;
reg   [0:0] tmp_8_reg_1579;
wire   [16:0] zi_V_2_fu_286_p2;
reg   [16:0] zi_V_2_reg_1584;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_9_reg_1589;
reg   [0:0] tmp_10_reg_1595;
wire   [16:0] zi_V_3_fu_320_p2;
reg   [16:0] zi_V_3_reg_1600;
wire    ap_CS_fsm_state4;
reg   [0:0] tmp_11_reg_1605;
reg   [0:0] tmp_12_reg_1611;
wire   [16:0] zi_V_4_fu_354_p2;
reg   [16:0] zi_V_4_reg_1616;
wire    ap_CS_fsm_state5;
reg   [0:0] tmp_13_reg_1621;
reg   [0:0] tmp_14_reg_1627;
wire   [16:0] zi_V_5_fu_388_p2;
reg   [16:0] zi_V_5_reg_1632;
wire    ap_CS_fsm_state6;
reg   [0:0] tmp_15_reg_1637;
reg   [0:0] tmp_16_reg_1643;
wire   [15:0] yi_V_8_fu_582_p3;
reg   [15:0] yi_V_8_reg_1648;
wire    ap_CS_fsm_state7;
wire   [15:0] xi_V_8_fu_589_p3;
reg   [15:0] xi_V_8_reg_1654;
reg   [11:0] r_2_reg_1660;
reg   [11:0] r_3_reg_1665;
wire   [16:0] zi_V_6_fu_628_p2;
reg   [16:0] zi_V_6_reg_1670;
reg   [0:0] tmp_17_reg_1675;
reg   [0:0] tmp_18_reg_1681;
wire   [15:0] yi_V_14_fu_742_p3;
reg   [15:0] yi_V_14_reg_1686;
wire    ap_CS_fsm_state8;
wire   [15:0] xi_V_14_fu_749_p3;
reg   [15:0] xi_V_14_reg_1692;
reg   [9:0] r_6_reg_1698;
reg   [9:0] r_7_reg_1703;
wire   [16:0] zi_V_7_fu_788_p2;
reg   [16:0] zi_V_7_reg_1708;
reg   [0:0] tmp_19_reg_1713;
reg   [0:0] tmp_20_reg_1719;
wire   [15:0] yi_V_20_fu_902_p3;
reg   [15:0] yi_V_20_reg_1724;
wire    ap_CS_fsm_state9;
wire   [15:0] xi_V_20_fu_909_p3;
reg   [15:0] xi_V_20_reg_1730;
reg   [7:0] r_10_reg_1736;
reg   [7:0] r_11_reg_1741;
wire   [16:0] zi_V_8_fu_948_p2;
reg   [16:0] zi_V_8_reg_1746;
reg   [0:0] tmp_21_reg_1751;
reg   [0:0] tmp_22_reg_1757;
wire   [15:0] yi_V_26_fu_1062_p3;
reg   [15:0] yi_V_26_reg_1762;
wire    ap_CS_fsm_state10;
wire   [15:0] xi_V_26_fu_1069_p3;
reg   [15:0] xi_V_26_reg_1768;
reg   [5:0] r_14_reg_1774;
reg   [5:0] r_15_reg_1779;
wire   [16:0] zi_V_9_fu_1108_p2;
reg   [16:0] zi_V_9_reg_1784;
reg   [0:0] tmp_23_reg_1789;
reg   [0:0] tmp_24_reg_1795;
wire   [16:0] zi_V_10_fu_1234_p2;
reg   [16:0] zi_V_10_reg_1800;
wire    ap_CS_fsm_state11;
wire   [15:0] yi_V_32_fu_1240_p3;
reg   [15:0] yi_V_32_reg_1805;
wire   [15:0] xi_V_32_fu_1247_p3;
reg   [15:0] xi_V_32_reg_1811;
reg   [0:0] tmp_25_reg_1817;
reg   [3:0] r_18_reg_1823;
reg   [3:0] r_19_reg_1828;
reg   [0:0] tmp_26_reg_1833;
wire   [16:0] zi_V_11_fu_1328_p2;
reg   [16:0] zi_V_11_reg_1838;
wire    ap_CS_fsm_state12;
reg   [0:0] tmp_28_reg_1843;
wire   [15:0] yi_V_38_fu_1416_p3;
reg   [15:0] yi_V_38_reg_1848;
wire   [15:0] xi_V_38_fu_1424_p3;
reg   [15:0] xi_V_38_reg_1854;
reg   [1:0] r_22_reg_1860;
reg   [1:0] r_23_reg_1865;
wire    ap_CS_fsm_state13;
wire   [0:0] tmp_1_fu_166_p3;
wire   [16:0] select_ln68_fu_174_p3;
wire   [16:0] add_ln68_fu_182_p2;
wire   [0:0] tmp_3_fu_196_p3;
wire   [16:0] add_ln1496_fu_212_p2;
wire   [16:0] select_ln1496_fu_204_p3;
wire   [16:0] add_ln1496_2_fu_247_p2;
wire   [16:0] select_ln1496_2_fu_240_p3;
wire   [16:0] add_ln1496_4_fu_281_p2;
wire   [16:0] select_ln1496_5_fu_274_p3;
wire   [16:0] add_ln1496_6_fu_315_p2;
wire   [16:0] select_ln1496_8_fu_308_p3;
wire   [16:0] add_ln1496_8_fu_349_p2;
wire   [16:0] select_ln1496_11_fu_342_p3;
wire   [16:0] add_ln1496_10_fu_383_p2;
wire   [16:0] select_ln1496_14_fu_376_p3;
wire   [14:0] yi_V_1_fu_431_p3;
wire   [14:0] yi_V_fu_417_p3;
wire  signed [14:0] yi_V_2_fu_438_p3;
wire   [13:0] xi_V_1_fu_424_p3;
wire   [13:0] xi_V_fu_410_p3;
wire   [13:0] xi_V_2_fu_449_p3;
wire   [12:0] trunc_ln2_fu_460_p4;
wire   [11:0] r_fu_474_p4;
wire   [14:0] zext_ln49_fu_456_p1;
wire  signed [14:0] sext_ln1333_fu_470_p1;
wire  signed [15:0] sext_ln50_fu_445_p1;
wire   [15:0] zext_ln1333_fu_484_p1;
wire   [15:0] yi_V_4_fu_506_p2;
wire   [15:0] yi_V_3_fu_494_p2;
wire   [14:0] xi_V_4_fu_500_p2;
wire   [14:0] xi_V_3_fu_488_p2;
wire   [14:0] xi_V_5_fu_519_p3;
wire   [15:0] yi_V_5_fu_512_p3;
wire   [12:0] r_1_fu_530_p4;
wire   [11:0] tmp_7_fu_544_p4;
wire   [15:0] zext_ln49_1_fu_526_p1;
wire  signed [15:0] sext_ln1333_1_fu_540_p1;
wire   [15:0] zext_ln1333_1_fu_554_p1;
wire   [15:0] yi_V_7_fu_576_p2;
wire   [15:0] yi_V_6_fu_564_p2;
wire   [15:0] xi_V_7_fu_570_p2;
wire   [15:0] xi_V_6_fu_558_p2;
wire   [16:0] add_ln1496_12_fu_623_p2;
wire   [16:0] select_ln1496_17_fu_616_p3;
wire  signed [15:0] sext_ln1333_2_fu_650_p1;
wire  signed [15:0] sext_ln1333_3_fu_653_p1;
wire   [15:0] yi_V_10_fu_671_p2;
wire   [15:0] yi_V_9_fu_661_p2;
wire   [15:0] xi_V_10_fu_666_p2;
wire   [15:0] xi_V_9_fu_656_p2;
wire   [15:0] yi_V_11_fu_676_p3;
wire   [10:0] r_4_fu_690_p4;
wire   [15:0] xi_V_11_fu_683_p3;
wire   [10:0] r_5_fu_704_p4;
wire  signed [15:0] sext_ln1333_4_fu_700_p1;
wire  signed [15:0] sext_ln1333_5_fu_714_p1;
wire   [15:0] yi_V_13_fu_736_p2;
wire   [15:0] yi_V_12_fu_724_p2;
wire   [15:0] xi_V_13_fu_730_p2;
wire   [15:0] xi_V_12_fu_718_p2;
wire   [16:0] add_ln1496_14_fu_783_p2;
wire   [16:0] select_ln1496_20_fu_776_p3;
wire  signed [15:0] sext_ln1333_6_fu_810_p1;
wire  signed [15:0] sext_ln1333_7_fu_813_p1;
wire   [15:0] yi_V_16_fu_831_p2;
wire   [15:0] yi_V_15_fu_821_p2;
wire   [15:0] xi_V_16_fu_826_p2;
wire   [15:0] xi_V_15_fu_816_p2;
wire   [15:0] yi_V_17_fu_836_p3;
wire   [8:0] r_8_fu_850_p4;
wire   [15:0] xi_V_17_fu_843_p3;
wire   [8:0] r_9_fu_864_p4;
wire  signed [15:0] sext_ln1333_8_fu_860_p1;
wire  signed [15:0] sext_ln1333_9_fu_874_p1;
wire   [15:0] yi_V_19_fu_896_p2;
wire   [15:0] yi_V_18_fu_884_p2;
wire   [15:0] xi_V_19_fu_890_p2;
wire   [15:0] xi_V_18_fu_878_p2;
wire   [16:0] add_ln1496_16_fu_943_p2;
wire   [16:0] select_ln1496_23_fu_936_p3;
wire  signed [15:0] sext_ln1333_10_fu_970_p1;
wire  signed [15:0] sext_ln1333_11_fu_973_p1;
wire   [15:0] yi_V_22_fu_991_p2;
wire   [15:0] yi_V_21_fu_981_p2;
wire   [15:0] xi_V_22_fu_986_p2;
wire   [15:0] xi_V_21_fu_976_p2;
wire   [15:0] yi_V_23_fu_996_p3;
wire   [6:0] r_12_fu_1010_p4;
wire   [15:0] xi_V_23_fu_1003_p3;
wire   [6:0] r_13_fu_1024_p4;
wire  signed [15:0] sext_ln1333_12_fu_1020_p1;
wire  signed [15:0] sext_ln1333_13_fu_1034_p1;
wire   [15:0] yi_V_25_fu_1056_p2;
wire   [15:0] yi_V_24_fu_1044_p2;
wire   [15:0] xi_V_25_fu_1050_p2;
wire   [15:0] xi_V_24_fu_1038_p2;
wire   [16:0] add_ln1496_18_fu_1103_p2;
wire   [16:0] select_ln1496_26_fu_1096_p3;
wire  signed [15:0] sext_ln1333_14_fu_1130_p1;
wire  signed [15:0] sext_ln1333_15_fu_1133_p1;
wire   [15:0] yi_V_28_fu_1151_p2;
wire   [15:0] yi_V_27_fu_1141_p2;
wire   [15:0] xi_V_28_fu_1146_p2;
wire   [15:0] xi_V_27_fu_1136_p2;
wire   [15:0] yi_V_29_fu_1156_p3;
wire   [4:0] r_16_fu_1170_p4;
wire   [15:0] xi_V_29_fu_1163_p3;
wire   [4:0] r_17_fu_1184_p4;
wire  signed [15:0] sext_ln1333_16_fu_1180_p1;
wire  signed [15:0] sext_ln1333_17_fu_1194_p1;
wire   [16:0] add_ln1496_20_fu_1229_p2;
wire   [16:0] select_ln1496_29_fu_1222_p3;
wire   [15:0] yi_V_31_fu_1216_p2;
wire   [15:0] yi_V_30_fu_1204_p2;
wire   [15:0] xi_V_31_fu_1210_p2;
wire   [15:0] xi_V_30_fu_1198_p2;
wire  signed [15:0] sext_ln1333_18_fu_1290_p1;
wire  signed [15:0] sext_ln1333_19_fu_1293_p1;
wire   [16:0] add_ln1496_22_fu_1323_p2;
wire   [16:0] select_ln1496_32_fu_1316_p3;
wire   [15:0] yi_V_34_fu_1311_p2;
wire   [15:0] yi_V_33_fu_1301_p2;
wire   [15:0] xi_V_34_fu_1306_p2;
wire   [15:0] xi_V_33_fu_1296_p2;
wire   [15:0] yi_V_35_fu_1334_p3;
wire   [2:0] r_20_fu_1356_p4;
wire   [15:0] xi_V_35_fu_1341_p3;
wire   [2:0] r_21_fu_1370_p4;
wire  signed [15:0] sext_ln1333_20_fu_1366_p1;
wire  signed [15:0] sext_ln1333_21_fu_1380_p1;
wire   [0:0] tmp_27_fu_1348_p3;
wire   [15:0] yi_V_37_fu_1402_p2;
wire   [15:0] yi_V_36_fu_1390_p2;
wire   [15:0] xi_V_37_fu_1396_p2;
wire   [15:0] xi_V_36_fu_1384_p2;
wire   [16:0] add_ln1496_24_fu_1459_p2;
wire   [16:0] select_ln1496_35_fu_1452_p3;
wire   [16:0] zi_V_12_fu_1464_p2;
wire  signed [15:0] sext_ln1333_22_fu_1478_p1;
wire  signed [15:0] sext_ln1333_23_fu_1481_p1;
wire   [0:0] tmp_29_fu_1470_p3;
wire   [15:0] yi_V_40_fu_1499_p2;
wire   [15:0] yi_V_39_fu_1489_p2;
wire   [15:0] xi_V_40_fu_1494_p2;
wire   [15:0] xi_V_39_fu_1484_p2;
wire   [15:0] yi_V_41_fu_1504_p3;
wire   [15:0] xi_V_41_fu_1512_p3;
reg   [15:0] ap_return_0_preg;
reg   [15:0] ap_return_1_preg;
reg   [1:0] ap_return_2_preg;
reg   [12:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 ap_return_0_preg = 16'd0;
#0 ap_return_1_preg = 16'd0;
#0 ap_return_2_preg = 2'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 16'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_return_0_preg <= yi_V_41_fu_1504_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 16'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_return_1_preg <= xi_V_41_fu_1512_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 2'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_return_2_preg <= flag_delay_V_write;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        r_10_reg_1736 <= {{yi_V_20_fu_902_p3[15:8]}};
        r_11_reg_1741 <= {{xi_V_20_fu_909_p3[15:8]}};
        tmp_21_reg_1751 <= zi_V_8_fu_948_p2[32'd16];
        tmp_22_reg_1757 <= zi_V_8_fu_948_p2[32'd16];
        xi_V_20_reg_1730 <= xi_V_20_fu_909_p3;
        yi_V_20_reg_1724 <= yi_V_20_fu_902_p3;
        zi_V_8_reg_1746 <= zi_V_8_fu_948_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r_14_reg_1774 <= {{yi_V_26_fu_1062_p3[15:10]}};
        r_15_reg_1779 <= {{xi_V_26_fu_1069_p3[15:10]}};
        tmp_23_reg_1789 <= zi_V_9_fu_1108_p2[32'd16];
        tmp_24_reg_1795 <= zi_V_9_fu_1108_p2[32'd16];
        xi_V_26_reg_1768 <= xi_V_26_fu_1069_p3;
        yi_V_26_reg_1762 <= yi_V_26_fu_1062_p3;
        zi_V_9_reg_1784 <= zi_V_9_fu_1108_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        r_18_reg_1823 <= {{yi_V_32_fu_1240_p3[15:12]}};
        r_19_reg_1828 <= {{xi_V_32_fu_1247_p3[15:12]}};
        tmp_25_reg_1817 <= zi_V_10_fu_1234_p2[32'd16];
        tmp_26_reg_1833 <= zi_V_10_fu_1234_p2[32'd16];
        xi_V_32_reg_1811 <= xi_V_32_fu_1247_p3;
        yi_V_32_reg_1805 <= yi_V_32_fu_1240_p3;
        zi_V_10_reg_1800 <= zi_V_10_fu_1234_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        r_22_reg_1860 <= {{yi_V_38_fu_1416_p3[15:14]}};
        r_23_reg_1865 <= {{xi_V_38_fu_1424_p3[15:14]}};
        tmp_28_reg_1843 <= zi_V_11_fu_1328_p2[32'd16];
        xi_V_38_reg_1854 <= xi_V_38_fu_1424_p3;
        yi_V_38_reg_1848 <= yi_V_38_fu_1416_p3;
        zi_V_11_reg_1838 <= zi_V_11_fu_1328_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        r_2_reg_1660 <= {{yi_V_8_fu_582_p3[15:4]}};
        r_3_reg_1665 <= {{xi_V_8_fu_589_p3[15:4]}};
        tmp_17_reg_1675 <= zi_V_6_fu_628_p2[32'd16];
        tmp_18_reg_1681 <= zi_V_6_fu_628_p2[32'd16];
        xi_V_8_reg_1654 <= xi_V_8_fu_589_p3;
        yi_V_8_reg_1648 <= yi_V_8_fu_582_p3;
        zi_V_6_reg_1670 <= zi_V_6_fu_628_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        r_6_reg_1698 <= {{yi_V_14_fu_742_p3[15:6]}};
        r_7_reg_1703 <= {{xi_V_14_fu_749_p3[15:6]}};
        tmp_19_reg_1713 <= zi_V_7_fu_788_p2[32'd16];
        tmp_20_reg_1719 <= zi_V_7_fu_788_p2[32'd16];
        xi_V_14_reg_1692 <= xi_V_14_fu_749_p3;
        yi_V_14_reg_1686 <= yi_V_14_fu_742_p3;
        zi_V_7_reg_1708 <= zi_V_7_fu_788_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_10_reg_1595 <= zi_V_2_fu_286_p2[32'd16];
        tmp_9_reg_1589 <= zi_V_2_fu_286_p2[32'd16];
        zi_V_2_reg_1584 <= zi_V_2_fu_286_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_11_reg_1605 <= zi_V_3_fu_320_p2[32'd16];
        tmp_12_reg_1611 <= zi_V_3_fu_320_p2[32'd16];
        zi_V_3_reg_1600 <= zi_V_3_fu_320_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_13_reg_1621 <= zi_V_4_fu_354_p2[32'd16];
        tmp_14_reg_1627 <= zi_V_4_fu_354_p2[32'd16];
        zi_V_4_reg_1616 <= zi_V_4_fu_354_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_15_reg_1637 <= zi_V_5_fu_388_p2[32'd16];
        tmp_16_reg_1643 <= zi_V_5_fu_388_p2[32'd16];
        zi_V_5_reg_1632 <= zi_V_5_fu_388_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_2_reg_1546 <= add_ln68_fu_182_p2[32'd16];
        tmp_4_reg_1557 <= zi_V_fu_218_p2[32'd16];
        tmp_5_reg_1563 <= zi_V_fu_218_p2[32'd16];
        tmp_reg_1538 <= alpha[32'd16];
        zi_V_reg_1552 <= zi_V_fu_218_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_6_reg_1573 <= zi_V_1_fu_252_p2[32'd16];
        tmp_8_reg_1579 <= zi_V_1_fu_252_p2[32'd16];
        zi_V_1_reg_1568 <= zi_V_1_fu_252_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_return_0 = yi_V_41_fu_1504_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_return_1 = xi_V_41_fu_1512_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_return_2 = flag_delay_V_write;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1496_10_fu_383_p2 = ($signed(zi_V_4_reg_1616) + $signed(17'd130817));

assign add_ln1496_12_fu_623_p2 = ($signed(zi_V_5_reg_1632) + $signed(17'd130945));

assign add_ln1496_14_fu_783_p2 = ($signed(zi_V_6_reg_1670) + $signed(17'd131009));

assign add_ln1496_16_fu_943_p2 = ($signed(zi_V_7_reg_1708) + $signed(17'd131041));

assign add_ln1496_18_fu_1103_p2 = ($signed(zi_V_8_reg_1746) + $signed(17'd131057));

assign add_ln1496_20_fu_1229_p2 = ($signed(zi_V_9_reg_1784) + $signed(17'd131064));

assign add_ln1496_22_fu_1323_p2 = ($signed(zi_V_10_reg_1800) + $signed(17'd131069));

assign add_ln1496_24_fu_1459_p2 = ($signed(zi_V_11_reg_1838) + $signed(17'd131070));

assign add_ln1496_2_fu_247_p2 = ($signed(zi_V_reg_1552) + $signed(17'd127059));

assign add_ln1496_4_fu_281_p2 = ($signed(zi_V_1_reg_1568) + $signed(17'd129035));

assign add_ln1496_6_fu_315_p2 = ($signed(zi_V_2_reg_1584) + $signed(17'd130050));

assign add_ln1496_8_fu_349_p2 = ($signed(zi_V_3_reg_1600) + $signed(17'd130561));

assign add_ln1496_fu_212_p2 = ($signed(add_ln68_fu_182_p2) + $signed(17'd123476));

assign add_ln68_fu_182_p2 = (select_ln68_fu_174_p3 + alpha);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign r_12_fu_1010_p4 = {{yi_V_23_fu_996_p3[15:9]}};

assign r_13_fu_1024_p4 = {{xi_V_23_fu_1003_p3[15:9]}};

assign r_16_fu_1170_p4 = {{yi_V_29_fu_1156_p3[15:11]}};

assign r_17_fu_1184_p4 = {{xi_V_29_fu_1163_p3[15:11]}};

assign r_1_fu_530_p4 = {{yi_V_5_fu_512_p3[15:3]}};

assign r_20_fu_1356_p4 = {{yi_V_35_fu_1334_p3[15:13]}};

assign r_21_fu_1370_p4 = {{xi_V_35_fu_1341_p3[15:13]}};

assign r_4_fu_690_p4 = {{yi_V_11_fu_676_p3[15:5]}};

assign r_5_fu_704_p4 = {{xi_V_11_fu_683_p3[15:5]}};

assign r_8_fu_850_p4 = {{yi_V_17_fu_836_p3[15:7]}};

assign r_9_fu_864_p4 = {{xi_V_17_fu_843_p3[15:7]}};

assign r_fu_474_p4 = {{xi_V_2_fu_449_p3[13:2]}};

assign select_ln1496_11_fu_342_p3 = ((tmp_12_reg_1611[0:0] == 1'b1) ? 17'd1022 : 17'd0);

assign select_ln1496_14_fu_376_p3 = ((tmp_14_reg_1627[0:0] == 1'b1) ? 17'd510 : 17'd0);

assign select_ln1496_17_fu_616_p3 = ((tmp_16_reg_1643[0:0] == 1'b1) ? 17'd254 : 17'd0);

assign select_ln1496_20_fu_776_p3 = ((tmp_18_reg_1681[0:0] == 1'b1) ? 17'd126 : 17'd0);

assign select_ln1496_23_fu_936_p3 = ((tmp_20_reg_1719[0:0] == 1'b1) ? 17'd62 : 17'd0);

assign select_ln1496_26_fu_1096_p3 = ((tmp_22_reg_1757[0:0] == 1'b1) ? 17'd30 : 17'd0);

assign select_ln1496_29_fu_1222_p3 = ((tmp_24_reg_1795[0:0] == 1'b1) ? 17'd16 : 17'd0);

assign select_ln1496_2_fu_240_p3 = ((tmp_5_reg_1563[0:0] == 1'b1) ? 17'd8026 : 17'd0);

assign select_ln1496_32_fu_1316_p3 = ((tmp_26_reg_1833[0:0] == 1'b1) ? 17'd6 : 17'd0);

assign select_ln1496_35_fu_1452_p3 = ((tmp_28_reg_1843[0:0] == 1'b1) ? 17'd4 : 17'd0);

assign select_ln1496_5_fu_274_p3 = ((tmp_8_reg_1579[0:0] == 1'b1) ? 17'd4074 : 17'd0);

assign select_ln1496_8_fu_308_p3 = ((tmp_10_reg_1595[0:0] == 1'b1) ? 17'd2044 : 17'd0);

assign select_ln1496_fu_204_p3 = ((tmp_3_fu_196_p3[0:0] == 1'b1) ? 17'd15192 : 17'd0);

assign select_ln68_fu_174_p3 = ((tmp_1_fu_166_p3[0:0] == 1'b1) ? 17'd12867 : 17'd118205);

assign sext_ln1333_10_fu_970_p1 = $signed(r_10_reg_1736);

assign sext_ln1333_11_fu_973_p1 = $signed(r_11_reg_1741);

assign sext_ln1333_12_fu_1020_p1 = $signed(r_12_fu_1010_p4);

assign sext_ln1333_13_fu_1034_p1 = $signed(r_13_fu_1024_p4);

assign sext_ln1333_14_fu_1130_p1 = $signed(r_14_reg_1774);

assign sext_ln1333_15_fu_1133_p1 = $signed(r_15_reg_1779);

assign sext_ln1333_16_fu_1180_p1 = $signed(r_16_fu_1170_p4);

assign sext_ln1333_17_fu_1194_p1 = $signed(r_17_fu_1184_p4);

assign sext_ln1333_18_fu_1290_p1 = $signed(r_18_reg_1823);

assign sext_ln1333_19_fu_1293_p1 = $signed(r_19_reg_1828);

assign sext_ln1333_1_fu_540_p1 = $signed(r_1_fu_530_p4);

assign sext_ln1333_20_fu_1366_p1 = $signed(r_20_fu_1356_p4);

assign sext_ln1333_21_fu_1380_p1 = $signed(r_21_fu_1370_p4);

assign sext_ln1333_22_fu_1478_p1 = $signed(r_22_reg_1860);

assign sext_ln1333_23_fu_1481_p1 = $signed(r_23_reg_1865);

assign sext_ln1333_2_fu_650_p1 = $signed(r_2_reg_1660);

assign sext_ln1333_3_fu_653_p1 = $signed(r_3_reg_1665);

assign sext_ln1333_4_fu_700_p1 = $signed(r_4_fu_690_p4);

assign sext_ln1333_5_fu_714_p1 = $signed(r_5_fu_704_p4);

assign sext_ln1333_6_fu_810_p1 = $signed(r_6_reg_1698);

assign sext_ln1333_7_fu_813_p1 = $signed(r_7_reg_1703);

assign sext_ln1333_8_fu_860_p1 = $signed(r_8_fu_850_p4);

assign sext_ln1333_9_fu_874_p1 = $signed(r_9_fu_864_p4);

assign sext_ln1333_fu_470_p1 = $signed(trunc_ln2_fu_460_p4);

assign sext_ln50_fu_445_p1 = yi_V_2_fu_438_p3;

assign tmp_1_fu_166_p3 = alpha[32'd16];

assign tmp_27_fu_1348_p3 = zi_V_11_fu_1328_p2[32'd16];

assign tmp_29_fu_1470_p3 = zi_V_12_fu_1464_p2[32'd16];

assign tmp_3_fu_196_p3 = add_ln68_fu_182_p2[32'd16];

assign tmp_7_fu_544_p4 = {{xi_V_5_fu_519_p3[14:3]}};

assign trunc_ln2_fu_460_p4 = {{yi_V_2_fu_438_p3[14:2]}};

assign xi_V_10_fu_666_p2 = ($signed(xi_V_8_reg_1654) + $signed(sext_ln1333_2_fu_650_p1));

assign xi_V_11_fu_683_p3 = ((tmp_9_reg_1589[0:0] == 1'b1) ? xi_V_10_fu_666_p2 : xi_V_9_fu_656_p2);

assign xi_V_12_fu_718_p2 = ($signed(xi_V_11_fu_683_p3) - $signed(sext_ln1333_4_fu_700_p1));

assign xi_V_13_fu_730_p2 = ($signed(xi_V_11_fu_683_p3) + $signed(sext_ln1333_4_fu_700_p1));

assign xi_V_14_fu_749_p3 = ((tmp_11_reg_1605[0:0] == 1'b1) ? xi_V_13_fu_730_p2 : xi_V_12_fu_718_p2);

assign xi_V_15_fu_816_p2 = ($signed(xi_V_14_reg_1692) - $signed(sext_ln1333_6_fu_810_p1));

assign xi_V_16_fu_826_p2 = ($signed(xi_V_14_reg_1692) + $signed(sext_ln1333_6_fu_810_p1));

assign xi_V_17_fu_843_p3 = ((tmp_13_reg_1621[0:0] == 1'b1) ? xi_V_16_fu_826_p2 : xi_V_15_fu_816_p2);

assign xi_V_18_fu_878_p2 = ($signed(xi_V_17_fu_843_p3) - $signed(sext_ln1333_8_fu_860_p1));

assign xi_V_19_fu_890_p2 = ($signed(xi_V_17_fu_843_p3) + $signed(sext_ln1333_8_fu_860_p1));

assign xi_V_1_fu_424_p3 = ((tmp_reg_1538[0:0] == 1'b1) ? 14'd4974 : 14'd14923);

assign xi_V_20_fu_909_p3 = ((tmp_15_reg_1637[0:0] == 1'b1) ? xi_V_19_fu_890_p2 : xi_V_18_fu_878_p2);

assign xi_V_21_fu_976_p2 = ($signed(xi_V_20_reg_1730) - $signed(sext_ln1333_10_fu_970_p1));

assign xi_V_22_fu_986_p2 = ($signed(xi_V_20_reg_1730) + $signed(sext_ln1333_10_fu_970_p1));

assign xi_V_23_fu_1003_p3 = ((tmp_17_reg_1675[0:0] == 1'b1) ? xi_V_22_fu_986_p2 : xi_V_21_fu_976_p2);

assign xi_V_24_fu_1038_p2 = ($signed(xi_V_23_fu_1003_p3) - $signed(sext_ln1333_12_fu_1020_p1));

assign xi_V_25_fu_1050_p2 = ($signed(xi_V_23_fu_1003_p3) + $signed(sext_ln1333_12_fu_1020_p1));

assign xi_V_26_fu_1069_p3 = ((tmp_19_reg_1713[0:0] == 1'b1) ? xi_V_25_fu_1050_p2 : xi_V_24_fu_1038_p2);

assign xi_V_27_fu_1136_p2 = ($signed(xi_V_26_reg_1768) - $signed(sext_ln1333_14_fu_1130_p1));

assign xi_V_28_fu_1146_p2 = ($signed(xi_V_26_reg_1768) + $signed(sext_ln1333_14_fu_1130_p1));

assign xi_V_29_fu_1163_p3 = ((tmp_21_reg_1751[0:0] == 1'b1) ? xi_V_28_fu_1146_p2 : xi_V_27_fu_1136_p2);

assign xi_V_2_fu_449_p3 = ((tmp_2_reg_1546[0:0] == 1'b1) ? xi_V_1_fu_424_p3 : xi_V_fu_410_p3);

assign xi_V_30_fu_1198_p2 = ($signed(xi_V_29_fu_1163_p3) - $signed(sext_ln1333_16_fu_1180_p1));

assign xi_V_31_fu_1210_p2 = ($signed(xi_V_29_fu_1163_p3) + $signed(sext_ln1333_16_fu_1180_p1));

assign xi_V_32_fu_1247_p3 = ((tmp_23_reg_1789[0:0] == 1'b1) ? xi_V_31_fu_1210_p2 : xi_V_30_fu_1198_p2);

assign xi_V_33_fu_1296_p2 = ($signed(xi_V_32_reg_1811) - $signed(sext_ln1333_18_fu_1290_p1));

assign xi_V_34_fu_1306_p2 = ($signed(xi_V_32_reg_1811) + $signed(sext_ln1333_18_fu_1290_p1));

assign xi_V_35_fu_1341_p3 = ((tmp_25_reg_1817[0:0] == 1'b1) ? xi_V_34_fu_1306_p2 : xi_V_33_fu_1296_p2);

assign xi_V_36_fu_1384_p2 = ($signed(xi_V_35_fu_1341_p3) - $signed(sext_ln1333_20_fu_1366_p1));

assign xi_V_37_fu_1396_p2 = ($signed(xi_V_35_fu_1341_p3) + $signed(sext_ln1333_20_fu_1366_p1));

assign xi_V_38_fu_1424_p3 = ((tmp_27_fu_1348_p3[0:0] == 1'b1) ? xi_V_37_fu_1396_p2 : xi_V_36_fu_1384_p2);

assign xi_V_39_fu_1484_p2 = ($signed(xi_V_38_reg_1854) - $signed(sext_ln1333_22_fu_1478_p1));

assign xi_V_3_fu_488_p2 = ($signed(zext_ln49_fu_456_p1) - $signed(sext_ln1333_fu_470_p1));

assign xi_V_40_fu_1494_p2 = ($signed(xi_V_38_reg_1854) + $signed(sext_ln1333_22_fu_1478_p1));

assign xi_V_41_fu_1512_p3 = ((tmp_29_fu_1470_p3[0:0] == 1'b1) ? xi_V_40_fu_1494_p2 : xi_V_39_fu_1484_p2);

assign xi_V_4_fu_500_p2 = ($signed(zext_ln49_fu_456_p1) + $signed(sext_ln1333_fu_470_p1));

assign xi_V_5_fu_519_p3 = ((tmp_4_reg_1557[0:0] == 1'b1) ? xi_V_4_fu_500_p2 : xi_V_3_fu_488_p2);

assign xi_V_6_fu_558_p2 = ($signed(zext_ln49_1_fu_526_p1) - $signed(sext_ln1333_1_fu_540_p1));

assign xi_V_7_fu_570_p2 = ($signed(zext_ln49_1_fu_526_p1) + $signed(sext_ln1333_1_fu_540_p1));

assign xi_V_8_fu_589_p3 = ((tmp_6_reg_1573[0:0] == 1'b1) ? xi_V_7_fu_570_p2 : xi_V_6_fu_558_p2);

assign xi_V_9_fu_656_p2 = ($signed(xi_V_8_reg_1654) - $signed(sext_ln1333_2_fu_650_p1));

assign xi_V_fu_410_p3 = ((tmp_reg_1538[0:0] == 1'b1) ? 14'd14924 : 14'd4975);

assign yi_V_10_fu_671_p2 = ($signed(yi_V_8_reg_1648) - $signed(sext_ln1333_3_fu_653_p1));

assign yi_V_11_fu_676_p3 = ((tmp_9_reg_1589[0:0] == 1'b1) ? yi_V_10_fu_671_p2 : yi_V_9_fu_661_p2);

assign yi_V_12_fu_724_p2 = ($signed(yi_V_11_fu_676_p3) + $signed(sext_ln1333_5_fu_714_p1));

assign yi_V_13_fu_736_p2 = ($signed(yi_V_11_fu_676_p3) - $signed(sext_ln1333_5_fu_714_p1));

assign yi_V_14_fu_742_p3 = ((tmp_11_reg_1605[0:0] == 1'b1) ? yi_V_13_fu_736_p2 : yi_V_12_fu_724_p2);

assign yi_V_15_fu_821_p2 = ($signed(yi_V_14_reg_1686) + $signed(sext_ln1333_7_fu_813_p1));

assign yi_V_16_fu_831_p2 = ($signed(yi_V_14_reg_1686) - $signed(sext_ln1333_7_fu_813_p1));

assign yi_V_17_fu_836_p3 = ((tmp_13_reg_1621[0:0] == 1'b1) ? yi_V_16_fu_831_p2 : yi_V_15_fu_821_p2);

assign yi_V_18_fu_884_p2 = ($signed(yi_V_17_fu_836_p3) + $signed(sext_ln1333_9_fu_874_p1));

assign yi_V_19_fu_896_p2 = ($signed(yi_V_17_fu_836_p3) - $signed(sext_ln1333_9_fu_874_p1));

assign yi_V_1_fu_431_p3 = ((tmp_reg_1538[0:0] == 1'b1) ? 15'd17845 : 15'd4975);

assign yi_V_20_fu_902_p3 = ((tmp_15_reg_1637[0:0] == 1'b1) ? yi_V_19_fu_896_p2 : yi_V_18_fu_884_p2);

assign yi_V_21_fu_981_p2 = ($signed(yi_V_20_reg_1724) + $signed(sext_ln1333_11_fu_973_p1));

assign yi_V_22_fu_991_p2 = ($signed(yi_V_20_reg_1724) - $signed(sext_ln1333_11_fu_973_p1));

assign yi_V_23_fu_996_p3 = ((tmp_17_reg_1675[0:0] == 1'b1) ? yi_V_22_fu_991_p2 : yi_V_21_fu_981_p2);

assign yi_V_24_fu_1044_p2 = ($signed(yi_V_23_fu_996_p3) + $signed(sext_ln1333_13_fu_1034_p1));

assign yi_V_25_fu_1056_p2 = ($signed(yi_V_23_fu_996_p3) - $signed(sext_ln1333_13_fu_1034_p1));

assign yi_V_26_fu_1062_p3 = ((tmp_19_reg_1713[0:0] == 1'b1) ? yi_V_25_fu_1056_p2 : yi_V_24_fu_1044_p2);

assign yi_V_27_fu_1141_p2 = ($signed(yi_V_26_reg_1762) + $signed(sext_ln1333_15_fu_1133_p1));

assign yi_V_28_fu_1151_p2 = ($signed(yi_V_26_reg_1762) - $signed(sext_ln1333_15_fu_1133_p1));

assign yi_V_29_fu_1156_p3 = ((tmp_21_reg_1751[0:0] == 1'b1) ? yi_V_28_fu_1151_p2 : yi_V_27_fu_1141_p2);

assign yi_V_2_fu_438_p3 = ((tmp_2_reg_1546[0:0] == 1'b1) ? yi_V_1_fu_431_p3 : yi_V_fu_417_p3);

assign yi_V_30_fu_1204_p2 = ($signed(yi_V_29_fu_1156_p3) + $signed(sext_ln1333_17_fu_1194_p1));

assign yi_V_31_fu_1216_p2 = ($signed(yi_V_29_fu_1156_p3) - $signed(sext_ln1333_17_fu_1194_p1));

assign yi_V_32_fu_1240_p3 = ((tmp_23_reg_1789[0:0] == 1'b1) ? yi_V_31_fu_1216_p2 : yi_V_30_fu_1204_p2);

assign yi_V_33_fu_1301_p2 = ($signed(yi_V_32_reg_1805) + $signed(sext_ln1333_19_fu_1293_p1));

assign yi_V_34_fu_1311_p2 = ($signed(yi_V_32_reg_1805) - $signed(sext_ln1333_19_fu_1293_p1));

assign yi_V_35_fu_1334_p3 = ((tmp_25_reg_1817[0:0] == 1'b1) ? yi_V_34_fu_1311_p2 : yi_V_33_fu_1301_p2);

assign yi_V_36_fu_1390_p2 = ($signed(yi_V_35_fu_1334_p3) + $signed(sext_ln1333_21_fu_1380_p1));

assign yi_V_37_fu_1402_p2 = ($signed(yi_V_35_fu_1334_p3) - $signed(sext_ln1333_21_fu_1380_p1));

assign yi_V_38_fu_1416_p3 = ((tmp_27_fu_1348_p3[0:0] == 1'b1) ? yi_V_37_fu_1402_p2 : yi_V_36_fu_1390_p2);

assign yi_V_39_fu_1489_p2 = ($signed(yi_V_38_reg_1848) + $signed(sext_ln1333_23_fu_1481_p1));

assign yi_V_3_fu_494_p2 = ($signed(sext_ln50_fu_445_p1) + $signed(zext_ln1333_fu_484_p1));

assign yi_V_40_fu_1499_p2 = ($signed(yi_V_38_reg_1848) - $signed(sext_ln1333_23_fu_1481_p1));

assign yi_V_41_fu_1504_p3 = ((tmp_29_fu_1470_p3[0:0] == 1'b1) ? yi_V_40_fu_1499_p2 : yi_V_39_fu_1489_p2);

assign yi_V_4_fu_506_p2 = ($signed(sext_ln50_fu_445_p1) - $signed(zext_ln1333_fu_484_p1));

assign yi_V_5_fu_512_p3 = ((tmp_4_reg_1557[0:0] == 1'b1) ? yi_V_4_fu_506_p2 : yi_V_3_fu_494_p2);

assign yi_V_6_fu_564_p2 = (yi_V_5_fu_512_p3 + zext_ln1333_1_fu_554_p1);

assign yi_V_7_fu_576_p2 = (yi_V_5_fu_512_p3 - zext_ln1333_1_fu_554_p1);

assign yi_V_8_fu_582_p3 = ((tmp_6_reg_1573[0:0] == 1'b1) ? yi_V_7_fu_576_p2 : yi_V_6_fu_564_p2);

assign yi_V_9_fu_661_p2 = ($signed(yi_V_8_reg_1648) + $signed(sext_ln1333_3_fu_653_p1));

assign yi_V_fu_417_p3 = ((tmp_reg_1538[0:0] == 1'b1) ? 15'd27793 : 15'd14923);

assign zext_ln1333_1_fu_554_p1 = tmp_7_fu_544_p4;

assign zext_ln1333_fu_484_p1 = r_fu_474_p4;

assign zext_ln49_1_fu_526_p1 = xi_V_5_fu_519_p3;

assign zext_ln49_fu_456_p1 = xi_V_2_fu_449_p3;

assign zi_V_10_fu_1234_p2 = (add_ln1496_20_fu_1229_p2 + select_ln1496_29_fu_1222_p3);

assign zi_V_11_fu_1328_p2 = (add_ln1496_22_fu_1323_p2 + select_ln1496_32_fu_1316_p3);

assign zi_V_12_fu_1464_p2 = (add_ln1496_24_fu_1459_p2 + select_ln1496_35_fu_1452_p3);

assign zi_V_1_fu_252_p2 = (add_ln1496_2_fu_247_p2 + select_ln1496_2_fu_240_p3);

assign zi_V_2_fu_286_p2 = (add_ln1496_4_fu_281_p2 + select_ln1496_5_fu_274_p3);

assign zi_V_3_fu_320_p2 = (add_ln1496_6_fu_315_p2 + select_ln1496_8_fu_308_p3);

assign zi_V_4_fu_354_p2 = (add_ln1496_8_fu_349_p2 + select_ln1496_11_fu_342_p3);

assign zi_V_5_fu_388_p2 = (add_ln1496_10_fu_383_p2 + select_ln1496_14_fu_376_p3);

assign zi_V_6_fu_628_p2 = (add_ln1496_12_fu_623_p2 + select_ln1496_17_fu_616_p3);

assign zi_V_7_fu_788_p2 = (add_ln1496_14_fu_783_p2 + select_ln1496_20_fu_776_p3);

assign zi_V_8_fu_948_p2 = (add_ln1496_16_fu_943_p2 + select_ln1496_23_fu_936_p3);

assign zi_V_9_fu_1108_p2 = (add_ln1496_18_fu_1103_p2 + select_ln1496_26_fu_1096_p3);

assign zi_V_fu_218_p2 = (add_ln1496_fu_212_p2 + select_ln1496_fu_204_p3);

endmodule //cordic_cordic_calculate
